import type { AppLocale } from "@/shared/i18n/locale";

export const PRODUCT_STATUS_FILTERS = [
  "all",
  "draft",
  "active",
  "out_of_stock",
  "archived",
] as const;
export type ProductStatusFilter = (typeof PRODUCT_STATUS_FILTERS)[number];

const PRODUCTS_VALIDATION_COPY = {
  vi: {
    nameRequired: "Vui lòng nhập tên sản phẩm",
    categoryRequired: "Vui lòng chọn loại hàng",
    unitRequired: "Vui lòng nhập đơn vị",
  },
  en: {
    nameRequired: "Please enter a product name",
    categoryRequired: "Please select a category",
    unitRequired: "Please enter a unit",
  },
} as const;

export function getProductsValidationCopy(locale: AppLocale) {
  return PRODUCTS_VALIDATION_COPY[locale] ?? PRODUCTS_VALIDATION_COPY.vi;
}

const PRODUCTS_COPY = {
  vi: {
    hub: {
      title: "Sản phẩm của tôi",
      createCta: "Thêm sản phẩm",
      emptyTitle: "Chưa có sản phẩm",
      emptyDescription:
        "Thêm sản phẩm nông sản để tạo lô hàng, mã QR truy xuất và đăng lên chợ giao thương.",
      filters: {
        all: "Tất cả",
        draft: "Nháp",
        active: "Đang bán",
        out_of_stock: "Hết hàng",
        archived: "Lưu trữ",
      },
      viewList: "Danh sách",
      viewTable: "Bảng kho",
      viewListTitle: "Danh sách liền khối",
      viewTableTitle: "Bảng dữ liệu kho",
      itemsCount: "sản phẩm",
      tableHeaders: {
        product: "Sản phẩm",
        status: "Trạng thái",
        price: "Giá / Đơn vị",
        location: "Vùng sản xuất",
        actions: "Thao tác",
      },
      loading: "Đang tải...",
      loadError: "Không thể tải danh sách sản phẩm.",
    },
    card: {
      edit: "Sửa",
      delete: "Xóa",
      createBatch: "Tạo lô",
      marketplace: "Đăng chợ",
      qr: "Tạo QR",
    },
    form: {
      createTitle: "Thêm sản phẩm",
      editTitle: "Chi tiết sản phẩm",
      createSubtitle: "Thông tin sản phẩm dùng cho lô hàng và truy xuất.",
      fields: {
        product: "Sản phẩm",
        name: "Tên sản phẩm",
        category: "Loại / ngành hàng",
        unit: "Đơn vị (kg, tấn, thùng…)",
        description: "Mô tả",
        productionLocation: "Địa điểm sản xuất",
        province: "Tỉnh / thành",
        ward: "Phường / xã",
        harvestDate: "Ngày thu hoạch",
        priceReference: "Giá tham chiếu",
        availableQuantity: "Số lượng có sẵn",
        isForMarketplace: "Đăng lên chợ giao thương",
        hasQr: "Bật truy xuất QR",
        certifications: "Chứng nhận liên kết",
      },
      photos: {
        label: "Ảnh sản phẩm",
        hint: "Tối đa 9 ảnh (JPEG, PNG, WebP).",
        add: "Thêm ảnh",
        limit: "Đã đạt tối đa 9 ảnh.",
        invalidType: "Định dạng ảnh không hợp lệ.",
        tooLarge: "Ảnh quá lớn (tối đa 5MB).",
        uploadError: "Không thể tải ảnh lên.",
        photoFallback: "Ảnh",
      },
      certificationsEmpty: "Thêm chứng nhận trong hồ sơ xanh trước.",
      save: "Lưu sản phẩm",
      cancel: "Huỷ",
      loading: "Đang tải...",
      loadError: "Không thể tải sản phẩm.",
      ui: {
        card1Title: "Thông tin chung",
        card1Tooltip: "Tên, loại, đặc tính và giá tham chiếu",
        namePlaceholder: "VD: Bưởi da xanh ruột hồng",
        unitPlaceholder: "VD: kg, tấn, thùng...",
        descriptionPlaceholder:
          "Bưởi da xanh Bến Tre, vỏ mỏng, múi to, ngọt thanh, ít hạt. Sản xuất theo tiêu chuẩn VietGAP.",
        qualityStandardsLabel: "Đặc tính sản phẩm",
        qualityStandardsEmpty: "Chưa có đặc tính nào. Chọn hoặc thêm bên dưới:",
        qualityStandardsHint: "Gợi ý nhanh:",
        qualityStandardsSuggestions: [
          "Ngọt",
          "Ít chua",
          "Hiếm",
          "Múi to",
          "Mọng nước",
          "Vỏ mỏng",
          "Hữu cơ",
        ],
        qualityStandardsInputPlaceholder: "Nhập đặc tính khác (VD: Không hạt...)",
        qualityStandardsAddBtn: "Thêm",
        statusLabel: "Tình trạng",
        statusActive: "Đang bán (Công khai)",
        statusDraft: "Lưu nháp",
        statusOutOfStock: "Hết hàng",
        priceUnitDefault: "VNĐ/kg",
        priceUnits: {
          tonne: "VNĐ/tấn",
          box: "VNĐ/hộp",
          bag: "VNĐ/túi",
          item: "VNĐ/sản phẩm",
        },
        priceReferencePlaceholder: "VD: 50,000",
        card2Title: "Nguồn gốc và thông tin sản phẩm",
        card2Tooltip: "Thông tin vùng trồng và tiêu chuẩn",
        productionLocationLabel: "Nơi sản xuất",
        productionLocationPlaceholder: "HTX Bưởi Da Xanh Bến Tre",
        provinceLabel: "Vùng trồng",
        provincePlaceholder: "Bến Tre",
        districtLabel: "Mùa vụ",
        districtPlaceholder: "Quanh năm",
        searchPlaceholder: "Tìm kiếm...",
        emptyText: "Không tìm thấy",
        harvestDateLabel: "Ngày thu hoạch",
        productionProcessLabel: "Quy trình sản xuất",
        productionProcessPlaceholder:
          "Sản xuất theo tiêu chuẩn VietGAP, tưới nhỏ giọt, không sử dụng chất kích thích tăng trưởng.",
        certificationsLabel: "Chứng nhận ( nếu có )",
        certificationsEmptyNote: "Chưa có chứng nhận nào được phê duyệt từ Hồ sơ Xanh.",
        addCertFromGreenProfile: "Thêm chứng nhận từ Hồ sơ Xanh",
        card3Title: "Hình ảnh/ Video sản phẩm",
        card3Tooltip: "Hình ảnh và video giới thiệu",
        photoGuidance:
          "Ảnh đầu tiên sẽ là ảnh đại diện. Kéo để sắp xếp thứ tự. Kích thước tối thiểu 800x600px để đạt được chất lượng tốt nhất.",
        card4Title: "Kết nối dữ liệu",
        card4Subtitle: "Kết nối nhật ký, lô hàng và mã QR truy xuất",
        card4Tooltip: "Kết nối dữ liệu lô và nhật ký",
        productionLogLabel: "Nhật ký sản xuất",
        logLinkedAfterPost: "Sẽ liên kết sau khi đăng",
        batchesLabel: "Lô hàng",
        viewBatches: "Xem lô hàng",
        batchCreatedAfterPost: "Sẽ tạo sau khi đăng",
        qrTraceabilityLabel: "QR truy xuất",
        qrLinked: "Đã liên kết QR",
        qrNotLinked: "Chưa liên kết",
        manageQrBtn: "Quản lý / Tạo mã QR",
        createQrBtn: "Tạo mã QR",
        qrRequiredAlert: "Hãy lưu hoặc đăng sản phẩm trước khi tạo mã QR truy xuất nhé!",
        refreshLinkBtn: "Làm mới liên kết",
        refreshSuccessToast: "Đã làm mới dữ liệu liên kết.",
        footerInfo: "Thông tin sẽ được kiểm tra trước khi hiển thị công khai.",
        saveDraftBtn: "Lưu (Nháp)",
        publishBtn: "Đăng bán sản phẩm",
        saveChangesBtn: "Lưu thay đổi",
      },
    },
    delete: {
      title: "Xóa sản phẩm",
      description:
        "Sản phẩm sẽ được chuyển sang trạng thái lưu trữ. Dữ liệu lô hàng và QR hiện có vẫn được giữ.",
      action: "Xóa sản phẩm",
      confirm: "Xóa sản phẩm này?",
    },
    toast: {
      createSuccess: "Đã thêm sản phẩm.",
      createError: "Không thể thêm sản phẩm. Vui lòng thử lại.",
      updateSuccess: "Đã cập nhật sản phẩm.",
      updateError: "Không thể cập nhật sản phẩm.",
      deleteSuccess: "Đã xóa sản phẩm.",
      deleteError: "Không thể xóa sản phẩm.",
    },
    detail: {
      actionsTitle: "Hành động",
      actionsDescription: "Tạo lô, đăng chợ hoặc sinh mã QR từ sản phẩm này.",
      createBatch: "Tạo lô hàng",
      marketplace: "Đăng lên chợ",
      generateQr: "Tạo mã QR",
      publish: "Chuyển thành Đang bán",
      unpublish: "Chuyển về Nháp",
    },
    createRail: {
      tips: {
        title: "Mẹo khi đăng bài",
        items: [
          "Cung cấp thông tin chính xác về nguồn gốc sản phẩm",
          "Thêm ảnh chất lượng cao, nhiều góc độ",
          "Mô tả rõ ràng để tăng cơ hội bán hàng",
        ],
      },
      qr: {
        title: "Tạo QR truy xuất",
        description:
          "Sau khi đăng sản phẩm, tạo mã QR để người dùng truy cập nguồn gốc chỉ bằng một lần quét.",
        notCreated: "Chưa tạo mã QR",
        createAfterPost: "Tạo mã QR sau khi đăng",
      },
      myProducts: {
        title: "Sản phẩm của bạn",
        viewAll: "Xem tất cả",
        empty: "Chưa có sản phẩm nào. Hãy đăng sản phẩm đầu tiên của bạn!",
        createCta: "Đăng sản phẩm mới",
      },
    },
  },
  en: {
    hub: {
      title: "My products",
      createCta: "Add product",
      emptyTitle: "No products yet",
      emptyDescription:
        "Add farm products to create batches, QR trace codes, and marketplace listings.",
      filters: {
        all: "All",
        draft: "Draft",
        active: "Active",
        out_of_stock: "Out of stock",
        archived: "Archived",
      },
      viewList: "List",
      viewTable: "Table",
      viewListTitle: "Unified card list",
      viewTableTitle: "Inventory data table",
      itemsCount: "products",
      tableHeaders: {
        product: "Product",
        status: "Status",
        price: "Price / Unit",
        location: "Production area",
        actions: "Actions",
      },
      loading: "Loading...",
      loadError: "Could not load products.",
    },
    card: {
      edit: "Edit",
      delete: "Delete",
      createBatch: "New batch",
      marketplace: "List on market",
      qr: "Create QR",
    },
    form: {
      createTitle: "Add product",
      editTitle: "Product details",
      createSubtitle: "Product info used for batches and traceability.",
      fields: {
        product: "Product",
        name: "Product name",
        category: "Category",
        unit: "Unit (kg, ton, crate…)",
        description: "Description",
        productionLocation: "Production location",
        province: "Province",
        ward: "Ward",
        harvestDate: "Harvest date",
        priceReference: "Reference price",
        availableQuantity: "Available quantity",
        isForMarketplace: "List on marketplace",
        hasQr: "Enable QR traceability",
        certifications: "Linked certifications",
      },
      photos: {
        label: "Product photos",
        hint: "Up to 9 images (JPEG, PNG, WebP).",
        add: "Add photo",
        limit: "Maximum of 9 photos reached.",
        invalidType: "Invalid image format.",
        tooLarge: "Image is too large (max 5MB).",
        uploadError: "Could not upload image.",
        photoFallback: "Photo",
      },
      certificationsEmpty: "Add certifications on your green profile first.",
      save: "Save product",
      cancel: "Cancel",
      loading: "Loading...",
      loadError: "Could not load product.",
      ui: {
        card1Title: "General Information",
        card1Tooltip: "Name, category, features and reference price",
        namePlaceholder: "e.g. Pink-fleshed green pomelo",
        unitPlaceholder: "e.g. kg, ton, box...",
        descriptionPlaceholder:
          "Ben Tre green pomelo, thin skin, juicy, sweet taste, few seeds. Grown to VietGAP standards.",
        qualityStandardsLabel: "Product Features",
        qualityStandardsEmpty: "No features added yet. Select or add below:",
        qualityStandardsHint: "Quick suggestions:",
        qualityStandardsSuggestions: [
          "Sweet",
          "Mildly sour",
          "Rare",
          "Large segments",
          "Juicy",
          "Thin skin",
          "Organic",
        ],
        qualityStandardsInputPlaceholder: "Enter custom feature (e.g. Seedless...)",
        qualityStandardsAddBtn: "Add",
        statusLabel: "Status",
        statusActive: "Active (Public)",
        statusDraft: "Save Draft",
        statusOutOfStock: "Out of Stock",
        priceUnitDefault: "VND/kg",
        priceUnits: {
          tonne: "VND/tonne",
          box: "VND/box",
          bag: "VND/bag",
          item: "VND/item",
        },
        priceReferencePlaceholder: "e.g. 50,000",
        card2Title: "Origin & Production Details",
        card2Tooltip: "Growing region and standard details",
        productionLocationLabel: "Production Location",
        productionLocationPlaceholder: "Ben Tre Pomelo Cooperative",
        provinceLabel: "Growing Region",
        provincePlaceholder: "Ben Tre",
        districtLabel: "Season",
        districtPlaceholder: "Year-round",
        searchPlaceholder: "Search...",
        emptyText: "Not found",
        harvestDateLabel: "Harvest Date",
        productionProcessLabel: "Production Process",
        productionProcessPlaceholder:
          "Produced under VietGAP standards, drip irrigation, no growth stimulants used.",
        certificationsLabel: "Certifications (if any)",
        certificationsEmptyNote: "No approved certifications from Green Profile yet.",
        addCertFromGreenProfile: "Add certification from Green Profile",
        card3Title: "Product Photos & Videos",
        card3Tooltip: "Showcase photos and videos",
        photoGuidance:
          "The first photo will be the cover image. Drag to reorder. Minimum 800x600px for best quality.",
        card4Title: "Data Integration",
        card4Subtitle: "Connect logs, batches and QR traceability",
        card4Tooltip: "Log and batch data integration",
        productionLogLabel: "Production Log",
        logLinkedAfterPost: "Will be linked after publishing",
        batchesLabel: "Batches",
        viewBatches: "View batches",
        batchCreatedAfterPost: "Will be created after publishing",
        qrTraceabilityLabel: "QR Traceability",
        qrLinked: "QR code linked",
        qrNotLinked: "Not linked yet",
        manageQrBtn: "Manage / Create QR",
        createQrBtn: "Create QR",
        qrRequiredAlert:
          "Please save or publish the product before creating a traceability QR code!",
        refreshLinkBtn: "Refresh Link",
        refreshSuccessToast: "Linked data refreshed.",
        footerInfo: "Information will be reviewed before displaying publicly.",
        saveDraftBtn: "Save (Draft)",
        publishBtn: "Publish Product",
        saveChangesBtn: "Save Changes",
      },
    },
    delete: {
      title: "Delete product",
      description: "The product will be archived. Existing batch and QR data will be kept.",
      action: "Delete product",
      confirm: "Delete this product?",
    },
    toast: {
      createSuccess: "Product added.",
      createError: "Could not add product. Please try again.",
      updateSuccess: "Product updated.",
      updateError: "Could not update product.",
      deleteSuccess: "Product deleted.",
      deleteError: "Could not delete product.",
    },
    detail: {
      actionsTitle: "Actions",
      actionsDescription: "Create batches, list on marketplace, or generate QR from this product.",
      createBatch: "Create batch",
      marketplace: "Post to marketplace",
      generateQr: "Generate QR",
      publish: "Set as Active",
      unpublish: "Set as Draft",
    },
    createRail: {
      tips: {
        title: "Posting tips",
        items: [
          "Provide accurate information about product origin",
          "Add high-quality photos from multiple angles",
          "Write a clear description to increase visibility",
        ],
      },
      qr: {
        title: "Create QR traceability",
        description:
          "After publishing your product, create a QR code so users can access its origin with a single scan.",
        notCreated: "QR not created yet",
        createAfterPost: "Create QR after publishing",
      },
      myProducts: {
        title: "Your products",
        viewAll: "View all",
        empty: "No products yet. Post your first product!",
        createCta: "Post new product",
      },
    },
  },
} as const;

export function getProductsCopy(locale: AppLocale) {
  return PRODUCTS_COPY[locale] ?? PRODUCTS_COPY.vi;
}
