import type { AppLocale } from "@/shared/i18n/locale";

export const SUPPLIER_COPY = {
  vi: {
    actions: {
      save: "Lưu nhà cung cấp",
      saved: "Đã lưu",
      unsave: "Bỏ lưu",
      review: "Đánh giá",
      writeReview: "Viết đánh giá",
      cancel: "Hủy",
      submit: "Gửi đánh giá",
      viewProfile: "Trang cá nhân",
      sendMessage: "Nhắn tin",
      viewProducts: "Sản phẩm",
    },
    savedTitle: "Nhà cung cấp đã lưu",
    savedSubtitle: "Danh sách các nhà cung cấp nông sản bạn đã lưu để theo dõi và kết nối",
    searchPlaceholder: "Tìm kiếm nhà cung cấp đã lưu...",
    clearSearch: "Xóa tìm kiếm",
    noSearchResultsTitle: "Không tìm thấy nhà cung cấp",
    noSearchResultsDesc: "Không tìm thấy nhà cung cấp nào phù hợp với từ khóa '{query}'",
    loadingSaved: "Đang tải danh sách nhà cung cấp đã lưu...",
    emptySavedTitle: "Chưa có nhà cung cấp nào được lưu",
    emptySavedDesc:
      "Hãy nhấn nút 'Lưu nhà cung cấp' ở trang cá nhân hoặc sản phẩm để dễ dàng theo dõi và liên hệ.",
    backToMarketplace: "Khám phá Chợ Nông Sản",
    totalSavedLabel: "Nhà cung cấp đã lưu",
    verifiedSupplier: "Đối tác nông sản",
    fallbackSupplierName: "Nhà cung cấp",
    defaultSupplierRole: "Đối tác nông nghiệp",
    quickContactTooltip: "Gửi tin nhắn trao đổi trực tiếp",
    viewProfileTooltip: "Xem thông tin & sản phẩm nhà cung cấp",
    reviewsTitle: "Đánh giá & Phản hồi",
    reviewsSummaryTitle: "Tổng hợp đánh giá",
    totalReviews: "{count} đánh giá",
    ratingLabel: "Đánh giá (1-5 sao):",
    reviewBodyPlaceholder:
      "Chia sẻ trải nghiệm làm việc, chất lượng nông sản và tiến độ giao hàng...",
    orderIdPlaceholder: "Mã đơn hàng đã hoàn thành (không bắt buộc)",
    noReviewsTitle: "Chưa có đánh giá nào",
    noReviewsDesc: "Hãy là người đầu tiên đánh giá nhà cung cấp này sau khi hoàn thành giao dịch.",
    toast: {
      saveSuccess: "Đã lưu nhà cung cấp thành công",
      unsaveSuccess: "Đã bỏ lưu nhà cung cấp",
      reviewSuccess: "Đã gửi đánh giá thành công",
      error: "Có lỗi xảy ra, vui lòng thử lại",
    },
  },
  en: {
    actions: {
      save: "Save supplier",
      saved: "Saved",
      unsave: "Unsave",
      review: "Review",
      writeReview: "Write a review",
      cancel: "Cancel",
      submit: "Submit review",
      viewProfile: "View Profile",
      sendMessage: "Message",
      viewProducts: "Products",
    },
    savedTitle: "Saved Suppliers",
    savedSubtitle: "List of suppliers you have bookmarked for quick reference and trade",
    searchPlaceholder: "Search saved suppliers...",
    clearSearch: "Clear search",
    noSearchResultsTitle: "No suppliers found",
    noSearchResultsDesc: "No saved suppliers match '{query}'",
    loadingSaved: "Loading saved suppliers...",
    emptySavedTitle: "No saved suppliers yet",
    emptySavedDesc:
      "Click the 'Save supplier' button on profiles or trade posts to keep track here.",
    backToMarketplace: "Explore Marketplace",
    totalSavedLabel: "Saved Suppliers",
    verifiedSupplier: "Agri Partner",
    fallbackSupplierName: "Supplier",
    defaultSupplierRole: "Agricultural Partner",
    quickContactTooltip: "Send direct message",
    viewProfileTooltip: "View supplier profile & products",
    reviewsTitle: "Reviews & Feedback",
    reviewsSummaryTitle: "Review Summary",
    totalReviews: "{count} reviews",
    ratingLabel: "Rating (1-5 stars):",
    reviewBodyPlaceholder:
      "Share your experience regarding product quality, delivery punctuality...",
    orderIdPlaceholder: "Completed Order ID (optional)",
    noReviewsTitle: "No reviews yet",
    noReviewsDesc: "Be the first to review this supplier after completing a deal.",
    toast: {
      saveSuccess: "Supplier saved successfully",
      unsaveSuccess: "Supplier removed from saved list",
      reviewSuccess: "Review submitted successfully",
      error: "An error occurred, please try again",
    },
  },
} as const;

export function getSupplierCopy(locale: AppLocale = "vi") {
  return SUPPLIER_COPY[locale] || SUPPLIER_COPY.vi;
}
