import type { AppLocale } from "@/shared/i18n/locale";
import { VIETSHOPX247_BASE_URL } from "@/shared/constants/external-links";

export { VIETSHOPX247_BASE_URL };

const TRACE_VALIDATION_COPY = {
  vi: {
    batchIdRequired: "Thiếu mã lô hàng",
    targetTypeRequired: "Loại đích QR không hợp lệ",
  },
  en: {
    batchIdRequired: "Batch is required",
    targetTypeRequired: "Invalid QR target type",
  },
} as const;

export function getTraceValidationCopy(locale: AppLocale) {
  return TRACE_VALIDATION_COPY[locale] ?? TRACE_VALIDATION_COPY.vi;
}

const TRACE_COPY = {
  vi: {
    qr: {
      title: "Quản lý mã QR",
      viewAndDownload: "Xem & Tải mã QR",
      dialogDescription: "Quét mã để xem thông tin truy xuất nguồn gốc sản phẩm",
      quotaTitle: "Hạn mức QR",
      quotaUsed: "Đã dùng",
      quotaLimit: "Giới hạn gói",
      generateCta: "Tạo mã QR",
      listTitle: "Mã QR của bạn",
      emptyTitle: "Chưa có mã QR",
      emptyDescription: "Tạo mã QR từ lô hàng hoặc sản phẩm để khách quét truy xuất.",
      columns: {
        code: "Mã",
        linked: "Gắn với",
        scans: "Lượt quét",
        actions: "Thao tác",
      },
      download: "Tải PNG",
      copyLink: "Sao chép link",
      copyLinkSuccess: "Đã sao chép link truy xuất.",
      copyLinkError: "Không thể sao chép link.",
      viewTrace: "Xem trang truy xuất",
      generating: "Đang tạo QR…",
      createFromBatchesCta: "Tạo QR từ lô hàng",
      loading: "Đang tải...",
      loadError: "Không thể tải danh sách mã QR.",
      apiUnavailable:
        "API QR trên backend chưa sẵn sàng. Bạn vẫn có thể quản lý lô hàng và nhật ký sản xuất.",
      quotaUnavailable: "Chưa kết nối được hạn mức QR.",
      quotaUnlimited: "Không giới hạn",
      linkedBatch: "Lô",
      linkedProduct: "Sản phẩm",
      remaining: "Còn lại",
      rail: {
        title: "Hạn mức & lô hàng",
        batches: "Quản lý lô hàng",
      },
      previewTitle: "Xem trước giao diện truy xuất",
      previewTitleWithCode: (code: string) => `Xem trước giao diện truy xuất (Mã: ${code})`,
      previewSubtitle: "Giao diện khách hàng sẽ nhìn thấy khi quét mã QR của lô hàng.",
      exportPdfBtn: "Xuất PDF nhãn QR",
      exportPdfTitle: "Xuất file PDF in nhãn QR",
      exportPdfSubtitle: "Chọn bố cục in và các mã QR để tạo file PDF in tem dán sản phẩm.",
      layoutLabel: "Bố cục in (Số tem / trang A4):",
      layout4: "4 nhãn / trang (kích thước lớn 5×5cm)",
      layout9: "9 nhãn / trang (kích thước vừa)",
      layout16: "16 nhãn / trang (kích thước nhỏ)",
      selectTokensLabel: "Chọn các mã QR cần in (Tối đa 16 mã):",
      selectAll: "Chọn tất cả",
      deselectAll: "Bỏ chọn",
      submitExport: "Tải file PDF in tem",
      exporting: "Đang tạo file PDF...",
      noTokenSelected: "Vui lòng chọn ít nhất 1 mã QR để xuất PDF.",
      labelSuffix: "tem/trang",
      sizeLarge: "Lớn 5x5cm",
      sizeMedium: "Vừa",
      sizeSmall: "Nhỏ",
      maxLimitError: "Tối đa 16 mã QR cho 1 lần xuất PDF",
      cancel: "Hủy",
      qrCodePrefix: "Mã QR #",
    },
    toast: {
      generateSuccess: "Đã tạo mã QR truy xuất.",
      generateError: "Không thể tạo mã QR. Kiểm tra hạn mức hoặc thử lại.",
      generateUnavailable: "API QR chưa sẵn sàng trên backend.",
    },
    public: {
      producer: "Nhà sản xuất",
      region: "Vùng sản xuất",
      harvest: "Ngày thu hoạch",
      certifications: "Chứng nhận",
      logSummary: "Nhật ký sản xuất",
      contact: "Liên hệ người bán",
      fullProfile: "Xem hồ sơ xanh",
      scanCount: "Lượt quét",
      poweredBy: "Truy xuất bởi VietGreenX",
      logCount: (n: number) => `${n} lượt ghi`,
      fallbackProductName: "Sản phẩm",
      notUpdated: "Chưa cập nhật",
      fallbackCertType: "Chứng nhận",
    },
    preview: {
      defaults: {
        traceProduct: "Sản phẩm truy xuất",
        demoProduct: "Rau cải sạch",
        traceDescription:
          "Thông tin quy trình sản xuất được ghi nhận từ hệ thống Nhật ký truy xuất GreenLife.",
        demoDescription: "Rau cải trồng theo tiêu chuẩn an toàn",
        demoLocation: "Châu Thành",
        goodAgriPractice: "Thực hành nông nghiệp tốt",
        organicCert: "Hữu cơ",
        internationalCert: "Chứng nhận cơ sở quốc tế",
        foodSafety: "An toàn thực phẩm",
        demoFarmName: "Trang trại GreenLife",
      },
      contact: {
        title: "Thông tin liên hệ",
        phone: "Số điện thoại",
        chat: "Chat trực tuyến",
        address: "Địa chỉ",
        notUpdated: "Chưa cập nhật",
        contactNow: "Liên hệ ngay",
        message: "Nhắn tin",
      },
      map: {
        title: "Vị trí vùng",
        notUpdated: "Chưa cập nhật",
        openMapHint: "Bấm để mở bản đồ ↗",
      },
      qr: {
        title: "Mã QR Sản phẩm",
        scanHint: "Quét để xem đầy đủ nguồn gốc thông tin",
        download: "Tải mã QR",
        fallbackCode: "Mã QR Truy xuất",
      },
      timeline: {
        title: "Nhật ký sản xuất tóm tắt",
        viewDetail: "Xem chi tiết",
        fallbackMilestone: "Quá trình",
      },
      reviews: {
        title: "Đánh giá của khách hàng",
        writeReview: "Viết đánh giá",
        modalTitle: "Đánh giá sản phẩm",
        ratingLabel: "Số sao đánh giá",
        reviewBodyLabel: "Nội dung đánh giá (không bắt buộc)",
        reviewBodyPlaceholder: "Chia sẻ nhận xét của bạn về chất lượng sản phẩm...",
        photosLabel: "Hình ảnh đính kèm (tối đa 5 ảnh)",
        addPhoto: "Thêm ảnh",
        photoLimitError: "Bạn chỉ được tải lên tối đa 5 ảnh.",
        cancel: "Hủy",
        submit: "Gửi đánh giá",
        loginToReview: "Đăng nhập để viết đánh giá",
        anonymousUser: "Người dùng",
        reviewCount: (n: number) => `${n} lượt đánh giá`,
        emptyState:
          "Chưa có đánh giá nào cho mã QR này. Hãy là người đầu tiên trải nghiệm và đánh giá!",
        loading: "Đang tải đánh giá...",
        toast: {
          alreadyExists: "Bạn đã gửi đánh giá cho mã QR này rồi.",
          success: "Đã gửi đánh giá thành công!",
          error: "Không thể gửi đánh giá. Vui lòng thử lại.",
        },
        comingSoon: "Tính năng đánh giá đang được phát triển.",
        filters: {
          all: "Tất cả",
          star5: "5 Sao (120)",
          star4: "4 Sao (5)",
          star3: "3 Sao (2)",
          star2: "2 Sao (1)",
          star1: "1 Sao (0)",
          hasComment: "Có Bình luận (85)",
          hasMedia: "Có Hình ảnh / Video (42)",
        },
      },
      pageTitle: "Kết quả truy xuất",
      pageSubtitle: "Chi tiết thông tin nguồn gốc sản phẩm",
      producerFallback: "Trang trại chưa cập nhật",
      producer: {
        title: "Thông tin sản phẩm và nhà sản xuất",
        producerLabel: "Nhà sản xuất",
        locationUpdating: "Đang cập nhật",
        phoneNotUpdated: "Chưa cập nhật",
        verified: "Đã xác thực",
        productionInfoTitle: "Thông tin sản xuất",
        mainProduct: "Sản phẩm chính:",
        area: "Diện tích:",
        areaUpdating: "Đang cập nhật",
      },
      certifications: {
        title: "Chứng nhận",
        fallbackType: "Chứng nhận",
        fallbackAuthority: "Chứng nhận chất lượng",
      },
      summary: {
        imgAlt: "Hình ảnh sản phẩm",
        verified: "Đã xác minh",
        organic: "Hữu cơ",
        noCode: "Không có",
        updating: "Đang cập nhật",
        qrCodeLabel: "Mã QR",
        harvestDateLabel: "Ngày thu hoạch",
        addressLabel: "Địa chỉ",
      },
      photos: {
        title: "Hình ảnh thực tế",
        viewAll: "Xem tất cả",
        imgAlt: (n: number) => `Hình ảnh thực tế ${n}`,
      },
      blockchainHash: {
        title: "Xác thực Blockchain Hash Layer",
        subtitle: "Tính toàn vẹn chuỗi Hash SHA-256 mã hóa mã lô và dữ liệu truy xuất",
        verified: "Chuỗi Hash Hợp Lệ (SHA-256 Verified)",
        tampered: "Cảnh báo: Dữ liệu Hash không toàn vẹn",
        uninitialized: "Chuỗi Hash đang được khởi tạo",
        chainLengthLabel: "Chiều dài chuỗi Block",
        blocks: "khối",
        lastVerifiedLabel: "Mã hóa gần nhất",
        cryptographicProof: "Bằng chứng mật mã học",
        proofAlgorithm: "Chuỗi Hash SHA-256",
        immutableData: "Dữ liệu được ghi nhận bất biến và không thể sửa đổi trái phép trên sổ cái.",
      },
    },
  },
  en: {
    qr: {
      title: "QR management",
      viewAndDownload: "View & Download QR",
      dialogDescription: "Scan code to view product origin information",
      quotaTitle: "QR quota",
      quotaUsed: "Used",
      quotaLimit: "Plan limit",
      generateCta: "Generate QR",
      listTitle: "Your QR codes",
      emptyTitle: "No QR codes yet",
      emptyDescription: "Generate QR from batches or products for public trace pages.",
      columns: {
        code: "Code",
        linked: "Linked to",
        scans: "Scans",
        actions: "Actions",
      },
      download: "Download PNG",
      copyLink: "Copy link",
      copyLinkSuccess: "Trace link copied.",
      copyLinkError: "Could not copy link.",
      viewTrace: "View trace page",
      generating: "Generating QR…",
      createFromBatchesCta: "Create QR from batch",
      loading: "Loading...",
      loadError: "Could not load QR codes.",
      apiUnavailable:
        "QR API is not available on the backend yet. You can still manage batches and production logs.",
      quotaUnavailable: "Could not load QR quota.",
      quotaUnlimited: "Unlimited",
      linkedBatch: "Batch",
      linkedProduct: "Product",
      remaining: "Remaining",
      rail: {
        title: "Quota & batches",
        batches: "Manage batches",
      },
      previewTitle: "Preview trace interface",
      previewTitleWithCode: (code: string) => `Preview trace interface (Code: ${code})`,
      previewSubtitle: "This is what customers see when they scan the batch QR code.",
      exportPdfBtn: "Export QR PDF",
      exportPdfTitle: "Export Printable QR Labels PDF",
      exportPdfSubtitle: "Select print layout and QR codes to generate printable PDF labels.",
      layoutLabel: "Print layout (Labels / A4 page):",
      layout4: "4 labels / page (large 5×5cm)",
      layout9: "9 labels / page (medium)",
      layout16: "16 labels / page (small)",
      selectTokensLabel: "Select QR codes to print (Max 16):",
      selectAll: "Select all",
      deselectAll: "Deselect all",
      submitExport: "Download PDF Labels",
      exporting: "Generating PDF...",
      noTokenSelected: "Please select at least 1 QR code to export PDF.",
      labelSuffix: "labels/page",
      sizeLarge: "Large 5x5cm",
      sizeMedium: "Medium",
      sizeSmall: "Small",
      maxLimitError: "Maximum 16 QR codes per export",
      cancel: "Cancel",
      qrCodePrefix: "QR Code #",
    },
    toast: {
      generateSuccess: "QR trace code generated.",
      generateError: "Could not generate QR. Check quota or try again.",
      generateUnavailable: "QR API is not available on the backend yet.",
    },
    public: {
      producer: "Producer",
      region: "Growing region",
      harvest: "Harvest date",
      certifications: "Certifications",
      logSummary: "Production log",
      contact: "Contact seller",
      fullProfile: "View green profile",
      scanCount: "Scans",
      poweredBy: "Traced by VietGreenX",
      logCount: (n: number) => `${n} log${n === 1 ? "" : "s"}`,
      fallbackProductName: "Product",
      notUpdated: "Not updated",
      fallbackCertType: "Certification",
    },
    preview: {
      defaults: {
        traceProduct: "Traceability Product",
        demoProduct: "Clean Vegetables",
        traceDescription:
          "Production process information recorded from GreenLife Traceability System.",
        demoDescription: "Vegetables grown according to safety standards",
        demoLocation: "Chau Thanh",
        goodAgriPractice: "Good Agricultural Practices",
        organicCert: "Organic",
        internationalCert: "International Facility Certification",
        foodSafety: "Food Safety",
        demoFarmName: "GreenLife Farm",
      },
      contact: {
        title: "Contact Information",
        phone: "Phone number",
        chat: "Online chat",
        address: "Address",
        notUpdated: "Not updated",
        contactNow: "Contact now",
        message: "Message",
      },
      map: {
        title: "Growing zone",
        notUpdated: "Not updated",
        openMapHint: "Click to open map ↗",
      },
      qr: {
        title: "Product QR Code",
        scanHint: "Scan to see full origin information",
        download: "Download QR",
        fallbackCode: "Trace QR Code",
      },
      timeline: {
        title: "Production log summary",
        viewDetail: "View details",
        fallbackMilestone: "Process",
      },
      reviews: {
        title: "Customer reviews",
        writeReview: "Write a review",
        modalTitle: "Review product",
        ratingLabel: "Rating",
        reviewBodyLabel: "Review comment (optional)",
        reviewBodyPlaceholder: "Share your thoughts about this product...",
        photosLabel: "Attached Photos (max 5)",
        addPhoto: "Add Photo",
        photoLimitError: "You can upload a maximum of 5 photos.",
        cancel: "Cancel",
        submit: "Submit review",
        loginToReview: "Log in to write a review",
        anonymousUser: "Anonymous",
        reviewCount: (n: number) => `${n} review${n === 1 ? "" : "s"}`,
        emptyState: "No reviews for this QR code yet. Be the first to review!",
        loading: "Loading reviews...",
        toast: {
          alreadyExists: "You have already reviewed this QR code.",
          success: "Review submitted successfully!",
          error: "Could not submit review. Please try again.",
        },
        comingSoon: "Review feature is under development.",
        filters: {
          all: "All",
          star5: "5 Stars (120)",
          star4: "4 Stars (5)",
          star3: "3 Stars (2)",
          star2: "2 Stars (1)",
          star1: "1 Star (0)",
          hasComment: "With Comments (85)",
          hasMedia: "With Media (42)",
        },
      },
      pageTitle: "Trace result",
      pageSubtitle: "Detailed product origin information",
      producerFallback: "Producer not updated",
      producer: {
        title: "Product & Producer Information",
        producerLabel: "Producer",
        locationUpdating: "Updating",
        phoneNotUpdated: "Not updated",
        verified: "Verified",
        productionInfoTitle: "Production Information",
        mainProduct: "Main product:",
        area: "Area:",
        areaUpdating: "Updating",
      },
      certifications: {
        title: "Certifications",
        fallbackType: "Certification",
        fallbackAuthority: "Quality certification",
      },
      summary: {
        imgAlt: "Product image",
        verified: "Verified",
        organic: "Organic",
        noCode: "N/A",
        updating: "Updating",
        qrCodeLabel: "QR Code",
        harvestDateLabel: "Harvest date",
        addressLabel: "Address",
      },
      photos: {
        title: "Farm photos",
        viewAll: "View all",
        imgAlt: (n: number) => `Farm photo ${n}`,
      },
      blockchainHash: {
        title: "Blockchain Hash Layer Verification",
        subtitle: "Cryptographic SHA-256 Hash Chain integrity for batch & trace data",
        verified: "SHA-256 Hash Chain Verified",
        tampered: "Warning: Hash Chain Integrity Compromised",
        uninitialized: "Hash Chain Initializing",
        chainLengthLabel: "Block Chain Length",
        blocks: "blocks",
        lastVerifiedLabel: "Last Encrypted",
        cryptographicProof: "Cryptographic Proof",
        proofAlgorithm: "SHA-256 Hash Chain",
        immutableData: "Data is recorded immutably on the ledger and tamper-proof.",
      },
    },
  },
} as const;

export function getTraceCopy(locale: AppLocale) {
  return TRACE_COPY[locale] ?? TRACE_COPY.vi;
}

export interface PublicTraceData {
  token: string;
  productName: string;
  producerName: string;
  provinceCode: string;
  harvestDate: string;
  imageUrl?: string;
  certifications: string[];
  scanCount?: number;
}

export const DEMO_TRACE_TOKEN = "demo";

export function getDemoTraceData(): PublicTraceData {
  return {
    token: DEMO_TRACE_TOKEN,
    productName: "Lúa ST25 hữu cơ",
    producerName: "HTX Nông nghiệp Xanh An",
    provinceCode: "An Giang",
    harvestDate: "15/03/2026",
    certifications: ["VietGAP", "Hữu cơ"],
    scanCount: 128,
  };
}
