export const QUOTATION_COPY = {
  vi: {
    title: "Quản lý Báo giá",
    subtitle: "Thương lượng giá và số lượng cung ứng nông sản với các đối tác",
    tabs: {
      received: "Báo giá nhận được",
      sent: "Báo giá đã gửi",
    },
    status: {
      pending: "Chờ xử lý",
      accepted: "Đã chấp nhận",
      rejected: "Đã từ chối",
      withdrawn: "Đã thu hồi",
      expired: "Hết hạn",
    },
    labels: {
      sender: "Người gửi",
      receiver: "Người nhận",
      member: "Thành viên",
      offeredPrice: "Giá đề xuất",
      offeredQuantity: "Số lượng đề xuất",
      deliveryDate: "Ngày giao hàng dự kiến",
      deliveryPrefix: "Giao ngày",
      notes: "Ghi chú thương lượng",
      rejectionReason: "Lý do từ chối: ",
      tradePost: "Bài đăng liên quan",
      createdAt: "Thời gian tạo",
      currencyUnit: "đ",
    },
    actions: {
      send: "Gửi báo giá",
      accept: "Chấp nhận",
      reject: "Từ chối",
      withdraw: "Thu hồi báo giá",
      cancel: "Hủy",
      submit: "Gửi ngay",
    },
    modal: {
      sendTitle: "Gửi báo giá nông sản",
      sendDescription: "Nhập thông tin đề xuất giá và số lượng cung ứng cho nhà mua/bán",
      offeredPricePlaceholder: "Nhập đơn giá (VD: 25000)",
      offeredQuantityPlaceholder: "Nhập số lượng (VD: 500)",
      unitPlaceholder: "Đơn vị (kg, tấn...)",
      notesPlaceholder: "Ghi chú về chất lượng, hình thức đóng gói, vận chuyển...",
    },
    rejectModal: {
      title: "Từ chối báo giá nông sản",
      description: "Bạn có thể nhập lý do từ chối gửi đến đối tác (không bắt buộc).",
      placeholder: "VD: Đã hết sản lượng, Giá chưa phù hợp...",
      cancel: "Hủy",
      confirm: "Xác nhận từ chối",
    },
    toast: {
      sendSuccess: "Đã gửi báo giá thành công!",
      acceptSuccess: "Đã chấp nhận báo giá!",
      rejectSuccess: "Đã từ chối báo giá!",
      withdrawSuccess: "Đã thu hồi báo giá!",
      error: "Có lỗi xảy ra, vui lòng thử lại.",
    },
    empty: {
      received: "Chưa có báo giá nào được gửi đến cho bạn.",
      sent: "Bạn chưa gửi báo giá nào.",
    },
    loading: "Đang tải danh sách báo giá...",
  },
  en: {
    title: "Quotations Management",
    subtitle: "Negotiate prices and supply quantities with agricultural partners",
    tabs: {
      received: "Received Quotations",
      sent: "Sent Quotations",
    },
    status: {
      pending: "Pending",
      accepted: "Accepted",
      rejected: "Rejected",
      withdrawn: "Withdrawn",
      expired: "Expired",
    },
    labels: {
      sender: "Sender",
      receiver: "Receiver",
      member: "Member",
      offeredPrice: "Offered Price",
      offeredQuantity: "Offered Quantity",
      deliveryDate: "Expected Delivery",
      deliveryPrefix: "Deliver by",
      notes: "Negotiation Notes",
      rejectionReason: "Rejection reason: ",
      tradePost: "Related Trade Post",
      createdAt: "Created At",
      currencyUnit: "VND",
    },
    actions: {
      send: "Send Quotation",
      accept: "Accept",
      reject: "Reject",
      withdraw: "Withdraw",
      cancel: "Cancel",
      submit: "Send Now",
    },
    modal: {
      sendTitle: "Send Agricultural Quotation",
      sendDescription: "Enter proposed price and supply quantity for buyer/supplier",
      offeredPricePlaceholder: "Enter unit price (e.g. 25000)",
      offeredQuantityPlaceholder: "Enter quantity (e.g. 500)",
      unitPlaceholder: "Unit (kg, ton...)",
      notesPlaceholder: "Notes on quality, packaging, transportation...",
    },
    rejectModal: {
      title: "Reject Agricultural Quotation",
      description: "You can enter a rejection reason to send to the partner (optional).",
      placeholder: "e.g. Out of stock, Price not suitable...",
      cancel: "Cancel",
      confirm: "Confirm Rejection",
    },
    toast: {
      sendSuccess: "Quotation sent successfully!",
      acceptSuccess: "Quotation accepted!",
      rejectSuccess: "Quotation rejected!",
      withdrawSuccess: "Quotation withdrawn!",
      error: "An error occurred, please try again.",
    },
    empty: {
      received: "No quotations received yet.",
      sent: "You have not sent any quotations yet.",
    },
    loading: "Loading quotations...",
  },
};
