import type { AppLocale } from "@/shared/i18n/locale";

const ORGANIZATION_VALIDATION_COPY = {
  vi: {
    nameRequired: "Vui lòng nhập tên tổ chức",
    userIdInvalid: "ID người dùng không hợp lệ",
    documentTypeRequired: "Vui lòng chọn loại giấy tờ",
    documentFrontUrlInvalid: "URL mặt trước không hợp lệ",
    documentBackUrlInvalid: "URL mặt sau không hợp lệ",
    tokenRequired: "Token mời không hợp lệ",
  },
  en: {
    nameRequired: "Please enter organization name",
    userIdInvalid: "Invalid user ID",
    documentTypeRequired: "Please select a document type",
    documentFrontUrlInvalid: "Invalid front document URL",
    documentBackUrlInvalid: "Invalid back document URL",
    tokenRequired: "Invalid invitation token",
  },
} as const;

export function getOrganizationValidationCopy(locale: AppLocale) {
  return ORGANIZATION_VALIDATION_COPY[locale] ?? ORGANIZATION_VALIDATION_COPY.vi;
}

const ORGANIZATION_COPY = {
  vi: {
    nav: {
      dashboard: "Tổ chức",
      members: "Thành viên",
      edit: "Chỉnh sửa",
    },
    dashboard: {
      title: "Tổ chức của tôi",
      subtitle: "Quản lý hồ sơ HTX / doanh nghiệp và thành viên.",
      loading: "Đang tải tổ chức…",
      loadError: "Không tải được thông tin tổ chức.",
      typeCooperative: "HTX",
      typeEnterprise: "Doanh nghiệp",
      emptyTitle: "Chưa có tổ chức",
      emptyDescription: "Tạo hoặc liên kết tổ chức để quản lý thành viên và đăng tin B2B.",
      manageMembers: "Quản lý thành viên",
      editOrg: "Chỉnh sửa hồ sơ",
      viewPublic: "Xem trang công khai",
      stats: {
        members: "Thành viên",
        listings: "Tin chợ",
        verified: "Xác minh",
      },
      verified: "Đã xác minh",
      notVerified: "Chưa xác minh",
      details: {
        province: "Tỉnh / Thành phố",
        address: "Địa chỉ",
        website: "Website",
        description: "Giới thiệu",
        registrationNumber: "Số đăng ký",
        slug: "Đường dẫn",
        followerCount: "Người theo dõi",
        createdAt: "Ngày thành lập",
        notProvided: "Chưa cập nhật",
      },
      rail: {
        title: "Hành động nhanh",
      },
    },
    create: {
      title: "Tạo tổ chức mới",
      subtitle: "Điền thông tin cơ bản để bắt đầu quản lý HTX hoặc doanh nghiệp.",
      submit: "Tạo tổ chức",
      success: "Đã tạo tổ chức thành công.",
      error: "Không thể tạo tổ chức. Vui lòng thử lại.",
      fields: {
        name: "Tên tổ chức",
        orgType: "Loại hình",
        taxId: "Mã số thuế",
        province: "Tỉnh / thành",
        address: "Địa chỉ",
        description: "Giới thiệu",
      },
      orgTypes: {
        cooperative: "Hợp tác xã",
        enterprise: "Doanh nghiệp",
        ngo: "Tổ chức phi lợi nhuận",
        government_agency: "Cơ quan nhà nước",
        other: "Khác",
      },
      placeholders: {
        province: "Chọn tỉnh/thành phố...",
        search: "Tìm kiếm...",
        empty: "Không tìm thấy",
      },
    },
    members: {
      title: "Thành viên",
      subtitle: "Mời và phân quyền thành viên trong tổ chức.",
      loading: "Đang tải thành viên…",
      loadError: "Không tải được danh sách thành viên.",
      inviteCta: "Mời thành viên",
      emptyTitle: "Chưa có thành viên",
      emptyDescription: "Mời thành viên để cùng quản lý sản phẩm và lô hàng.",
      columns: {
        name: "Tên",
        role: "Vai trò",
        status: "Trạng thái",
        joined: "Tham gia",
        actions: "Thao tác",
      },
      roles: {
        admin: "Quản trị",
        member: "Thành viên",
        viewer: "Chỉ xem",
      },
      status: {
        active: "Đang hoạt động",
        invited: "Đã mời",
      },
      invite: {
        title: "Mời thành viên",
        description: "Nhập ID người dùng (UUID) và vai trò trong tổ chức.",
        userId: "ID người dùng",
        role: "Vai trò",
        submit: "Gửi lời mời",
        success: "Đã gửi lời mời.",
        linkCopied: "Đã sao chép link mời vào clipboard.",
        error: "Không thể mời thành viên.",
      },
      remove: {
        action: "Xóa",
        confirmTitle: "Xóa thành viên?",
        confirmDescription: "Thành viên sẽ mất quyền truy cập tổ chức.",
        confirm: "Xóa thành viên",
        cancel: "Huỷ",
        success: "Đã xóa thành viên.",
        error: "Không thể xóa thành viên.",
      },
      updateRole: {
        success: "Đã cập nhật vai trò.",
        error: "Không thể cập nhật vai trò.",
      },
      rail: {
        title: "Mời & phân quyền",
      },
    },
    delete: {
      title: "Xóa tổ chức",
      description: "Hành động này xóa vĩnh viễn tổ chức và mọi thành viên sẽ mất quyền truy cập.",
      action: "Xóa tổ chức",
      dialogTitle: "Xác nhận xóa tổ chức",
      dialogDescription: "Bạn có chắc muốn xóa tổ chức này? Hành động không thể hoàn tác.",
      confirm: "Xóa tổ chức",
      cancel: "Huỷ",
      deleting: "Đang xóa…",
      success: "Đã xóa tổ chức.",
      error: "Không thể xóa tổ chức.",
    },
    edit: {
      title: "Chỉnh sửa tổ chức",
      subtitle: "Thông tin hiển thị trên trang công khai.",
      loading: "Đang tải…",
      loadError: "Không tải được thông tin tổ chức.",
      saved: "Đã lưu thay đổi.",
      saveError: "Không thể lưu. Vui lòng thử lại.",
      fields: {
        name: "Tên tổ chức",
        orgType: "Loại hình",
        taxId: "Mã số thuế",
        province: "Tỉnh / thành",
        address: "Địa chỉ",
        description: "Giới thiệu",
        logo: "Logo",
        cover: "Ảnh bìa",
        registrationCert: "Giấy đăng ký (PDF)",
      },
      placeholders: {
        province: "Chọn tỉnh/thành phố...",
        search: "Tìm kiếm...",
        empty: "Không tìm thấy",
      },
      save: "Lưu",
      cancel: "Huỷ",
    },
    verification: {
      title: "Xác minh tổ chức",
      description: "Gửi hồ sơ giấy tờ để nâng cấp mức xác minh (basic).",
      documentType: "Loại giấy tờ",
      documentFrontUrl: "URL mặt trước",
      documentBackUrl: "URL mặt sau (tuỳ chọn)",
      submit: "Gửi yêu cầu xác minh",
      success: "Đã gửi yêu cầu xác minh.",
      error: "Không thể gửi yêu cầu.",
      documentTypes: {
        business_registration: "Giấy đăng ký kinh doanh",
        cooperative_license: "Giấy phép HTX",
      },
    },
    acceptInvite: {
      title: "Lời mời tham gia tổ chức",
      description: "Bạn được mời tham gia một tổ chức trên VietGreenX.",
      accept: "Chấp nhận",
      decline: "Từ chối",
      accepted: "Đã tham gia tổ chức.",
      declined: "Đã từ chối lời mời.",
      error: "Không thể xử lý lời mời.",
      missingToken: "Link mời không hợp lệ.",
      backToFeed: "Về bảng tin",
      loading: "Đang xử lý…",
    },
    publicPage: {
      breadcrumbHome: "Trang chủ",
      breadcrumbOrg: "Tổ chức",
      notFound: "Không tìm thấy tổ chức",
    },
  },
  en: {
    nav: {
      dashboard: "Organization",
      members: "Members",
      edit: "Edit",
    },
    dashboard: {
      title: "My organization",
      subtitle: "Manage cooperative / enterprise profile and members.",
      loading: "Loading organization…",
      loadError: "Could not load organization.",
      typeCooperative: "Cooperative",
      typeEnterprise: "Enterprise",
      emptyTitle: "No organization yet",
      emptyDescription: "Create or link an organization to manage members and B2B listings.",
      manageMembers: "Manage members",
      editOrg: "Edit profile",
      viewPublic: "View public page",
      stats: {
        members: "Members",
        listings: "Market listings",
        verified: "Verification",
      },
      verified: "Verified",
      notVerified: "Not verified",
      details: {
        province: "Province / City",
        address: "Address",
        website: "Website",
        description: "About",
        registrationNumber: "Registration No.",
        slug: "Public slug",
        followerCount: "Followers",
        createdAt: "Founded",
        notProvided: "Not provided",
      },
      rail: {
        title: "Quick actions",
      },
    },
    create: {
      title: "Create organization",
      subtitle: "Fill in basic info to start managing your cooperative or enterprise.",
      submit: "Create organization",
      success: "Organization created successfully.",
      error: "Could not create organization. Please try again.",
      fields: {
        name: "Organization name",
        orgType: "Type",
        taxId: "Tax ID",
        province: "Province",
        address: "Address",
        description: "About",
      },
      orgTypes: {
        cooperative: "Cooperative",
        enterprise: "Enterprise",
        ngo: "Non-profit",
        government_agency: "Government agency",
        other: "Other",
      },
      placeholders: {
        province: "Select province/city...",
        search: "Search...",
        empty: "Not found",
      },
    },
    members: {
      title: "Members",
      subtitle: "Invite and assign roles within your organization.",
      loading: "Loading members…",
      loadError: "Could not load members.",
      inviteCta: "Invite member",
      emptyTitle: "No members yet",
      emptyDescription: "Invite members to manage products and batches together.",
      columns: {
        name: "Name",
        role: "Role",
        status: "Status",
        joined: "Joined",
        actions: "Actions",
      },
      roles: {
        admin: "Admin",
        member: "Member",
        viewer: "Viewer",
      },
      status: {
        active: "Active",
        invited: "Invited",
      },
      invite: {
        title: "Invite member",
        description: "Enter the user ID (UUID) and organization role.",
        userId: "User ID",
        role: "Role",
        submit: "Send invitation",
        success: "Invitation sent.",
        linkCopied: "Invite link copied to clipboard.",
        error: "Could not invite member.",
      },
      remove: {
        action: "Remove",
        confirmTitle: "Remove member?",
        confirmDescription: "This member will lose access to the organization.",
        confirm: "Remove member",
        cancel: "Cancel",
        success: "Member removed.",
        error: "Could not remove member.",
      },
      updateRole: {
        success: "Role updated.",
        error: "Could not update role.",
      },
      rail: {
        title: "Invite & roles",
      },
    },
    delete: {
      title: "Delete organization",
      description: "This permanently deletes the organization and revokes access for all members.",
      action: "Delete organization",
      dialogTitle: "Confirm organization deletion",
      dialogDescription:
        "Are you sure you want to delete this organization? This cannot be undone.",
      confirm: "Delete organization",
      cancel: "Cancel",
      deleting: "Deleting…",
      success: "Organization deleted.",
      error: "Could not delete organization.",
    },
    edit: {
      title: "Edit organization",
      subtitle: "Info shown on the public page.",
      loading: "Loading…",
      loadError: "Could not load organization.",
      saved: "Changes saved.",
      saveError: "Could not save. Please try again.",
      fields: {
        name: "Organization name",
        orgType: "Type",
        taxId: "Tax ID",
        province: "Province",
        address: "Address",
        description: "About",
        logo: "Logo",
        cover: "Cover image",
        registrationCert: "Registration certificate (PDF)",
      },
      placeholders: {
        province: "Select province/city...",
        search: "Search...",
        empty: "Not found",
      },
      save: "Save",
      cancel: "Cancel",
    },
    verification: {
      title: "Verify organization",
      description: "Submit document URLs to request basic verification.",
      documentType: "Document type",
      documentFrontUrl: "Front side URL",
      documentBackUrl: "Back side URL (optional)",
      submit: "Submit verification",
      success: "Verification request submitted.",
      error: "Could not submit request.",
      documentTypes: {
        business_registration: "Business registration",
        cooperative_license: "Cooperative license",
      },
    },
    acceptInvite: {
      title: "Organization invitation",
      description: "You have been invited to join an organization on VietGreenX.",
      accept: "Accept",
      decline: "Decline",
      accepted: "You joined the organization.",
      declined: "Invitation declined.",
      error: "Could not process invitation.",
      missingToken: "Invalid invitation link.",
      backToFeed: "Back to feed",
      loading: "Processing…",
    },
    publicPage: {
      breadcrumbHome: "Home",
      breadcrumbOrg: "Organization",
      notFound: "Organization not found",
    },
  },
} as const;

export function getOrganizationCopy(locale: AppLocale) {
  return ORGANIZATION_COPY[locale] ?? ORGANIZATION_COPY.vi;
}

export function getMemberRoleLabel(role: string, locale: AppLocale): string {
  const roles = getOrganizationCopy(locale).members.roles;
  if (role === "org_admin") return roles.admin;
  if (role === "org_viewer") return roles.viewer;
  return roles.member;
}
