import type { AppLocale } from "@/shared/i18n/locale";

export const ORGS_DIRECTORY_COPY = {
  vi: {
    title: "Khám phá Hợp Tác Xã",
    subtitle:
      "Thiết lập kết nối với các đối tác nông nghiệp để quản lý chuỗi cung ứng, giúp bạn tập trung vào kinh doanh.",
    searchPlaceholder: "Tìm tên HTX...",
    recommended: "Gợi ý cho bạn",
    noAddress: "Chưa cập nhật địa chỉ",
    cooperative: "Hợp tác xã nông nghiệp",
    enterprise: "Doanh nghiệp",
    description: "chuyên cung cấp các sản phẩm nông sản đạt tiêu chuẩn, đảm bảo chất lượng.",
    followers: "theo dõi",
    members: "thành viên",
    products: "sản phẩm",
    followBtn: "+ Theo dõi",
    followingBtn: "✓ Đang theo dõi",
    verified: "Đã xác thực",
    filterAll: "Tất cả",
    filterCoop: "Hợp tác xã",
    filterEnterprise: "Doanh nghiệp",
    filterVerified: "Đã xác thực",
    emptyResults: "Không tìm thấy hợp tác xã hoặc doanh nghiệp phù hợp.",
    viewProfileBtn: "Xem chi tiết",
  },
  en: {
    title: "Explore Cooperatives",
    subtitle:
      "Establish connections with agricultural partners to manage your supply chain, helping you focus on business.",
    searchPlaceholder: "Search cooperative name...",
    recommended: "Recommended for you",
    noAddress: "Address not updated",
    cooperative: "Agricultural cooperative",
    enterprise: "Enterprise",
    description: "specializes in providing quality agricultural products that meet standards.",
    followers: "followers",
    members: "members",
    products: "products",
    followBtn: "+ Follow",
    followingBtn: "✓ Following",
    verified: "Verified",
    filterAll: "All",
    filterCoop: "Cooperatives",
    filterEnterprise: "Enterprises",
    filterVerified: "Verified",
    emptyResults: "No matching cooperatives or enterprises found.",
    viewProfileBtn: "View Details",
  },
} as const satisfies Record<AppLocale, Record<string, unknown>>;
