import type { AppLocale } from "@/shared/i18n/locale";
import { UserRole } from "@/shared/auth";

const PROFILE_VALIDATION_COPY = {
  vi: {
    displayNameMin: "Tối thiểu 2 ký tự",
    displayNameMax: "Tối đa 100 ký tự",
    bioMax: "Tối đa 500 ký tự",
    websiteMax: "Tối đa 255 ký tự",
    provinceMax: "Tối đa 100 ký tự",
    wardMax: "Tối đa 100 ký tự",
  },
  en: {
    displayNameMin: "At least 2 characters",
    displayNameMax: "Up to 100 characters",
    bioMax: "Up to 500 characters",
    websiteMax: "Up to 255 characters",
    provinceMax: "Up to 100 characters",
    wardMax: "Up to 100 characters",
  },
} as const;

export function getProfileValidationCopy(locale: AppLocale) {
  return PROFILE_VALIDATION_COPY[locale] ?? PROFILE_VALIDATION_COPY.vi;
}

const PROFILE_COPY = {
  vi: {
    view: {
      title: "Hồ sơ của tôi",
      subtitle: "Chỉ bạn thấy trang này — cập nhật khi bạn muốn.",
      edit: "Chỉnh sửa hồ sơ",
      noBio: "Chưa có giới thiệu.",
      noLocation: "Chưa có địa chỉ.",
      roles: {
        [UserRole.CONSUMER]: "Người mua / dùng app",
        [UserRole.SELLER]: "Người bán cá nhân",
        [UserRole.COOPERATIVE]: "Hợp tác xã",
        [UserRole.ENTERPRISE]: "Doanh nghiệp",
        [UserRole.EXPERT]: "Chuyên gia",
        [UserRole.ADMIN]: "Quản trị",
        [UserRole.GUEST]: "Khách",
      },
      loading: "Đang tải hồ sơ...",
      loadError: "Không thể tải hồ sơ.",
    },
    screen: {
      postsTab: "Bài viết",
      postsTitle: "Bài viết của bạn",
      postsSubtitle: "Chia sẻ cập nhật mùa vụ và thu hoạch",
      introTitle: "Giới thiệu",
      vgxTitle: "VietGreenX",
      statPosts: "bài viết",
      statFollowers: "theo dõi",
      statFollowing: "đang theo",
      shortcutMarketplace: "Chợ nông sản",
      shortcutGreenProfile: "Hồ sơ xanh",
      photosTitle: "Ảnh",
      viewAllPhotos: "Xem tất cả ảnh",
      noPhotos: "Chưa có ảnh nào",
      transactionHistory: {
        title: "Lịch sử giao dịch & kết nối",
        subtitle: "Báo giá và kết nối giao thương giữa các bên",
        sent: "Đã gửi",
        received: "Đã nhận",
        statusPending: "Đang chờ",
        statusAccepted: "Đã chấp nhận",
        statusRejected: "Đã từ chối",
        statusExpired: "Hết hạn",
        statusWithdrawn: "Đã rút",
        emptyTitle: "Chưa có lịch sử giao dịch",
        emptyDescription: "Chưa có giao dịch hoặc kết nối báo giá nào được thực hiện.",
        productLabel: "Sản phẩm",
        quantityLabel: "Số lượng",
        partnerLabel: "Đối tác",
        dateLabel: "Thời gian",
      },
    },
    edit: {
      title: "Chỉnh sửa hồ sơ",
      subtitle: "Cập nhật thông tin hiển thị công khai.",
      changeAvatar: "Đổi ảnh đại diện",
      avatarUploading: "Đang tải lên...",
      avatarHint: "PNG, JPG hoặc WebP, tối đa 5MB.",
      avatarSaved: "Đã cập nhật ảnh đại diện.",
      avatarSaveError: "Không thể tải ảnh lên.",
      avatarInvalidType: "Chỉ hỗ trợ PNG, JPG hoặc WebP.",
      avatarTooLarge: "Ảnh tối đa 5MB.",
      displayName: "Tên hiển thị",
      bio: "Giới thiệu",
      bioHint: "Tối đa 500 ký tự",
      website: "Website",
      websitePlaceholder: "https://...",
      address: {
        locationTitle: "Địa chỉ",
        province: "Tỉnh / Thành phố",
        ward: "Phường / Xã",
        provincePlaceholder: "Chọn tỉnh / thành phố",
        wardPlaceholder: "Chọn phường / xã",
        searchPlaceholder: "Tìm kiếm...",
        emptyText: "Không tìm thấy.",
        loading: "Đang tải danh sách địa danh...",
        loadError: "Không thể tải danh sách địa danh. Thử lại sau.",
        mergerNotice: "Theo địa giới hành chính sau sáp nhập 2025 (34 tỉnh, thành phố).",
        legacyHint: "Địa danh đã lưu không còn trong danh sách — hãy chọn lại nếu cần cập nhật.",
      },
      save: "Lưu thay đổi",
      saved: "Đã cập nhật hồ sơ.",
      saveError: "Không thể lưu hồ sơ.",
      back: "Quay lại hồ sơ",
    },
    banner: {
      dismiss: "Đóng gợi ý",
      greenProfile: {
        title: "Bắt đầu bán hàng",
        description:
          "Tạo Hồ sơ xanh để đăng sản phẩm, quản lý mùa vụ và tạo mã QR truy xuất nguồn gốc.",
        cta: "Tạo Hồ sơ xanh",
      },
      orgSetup: {
        title: "Thiết lập tổ chức",
        description:
          "Tạo hồ sơ tổ chức để mở khoá quản lý thành viên, giao dịch B2B và truy xuất theo lô.",
        cta: "Thiết lập ngay",
      },
      profileCompletion: {
        title: "Hoàn thiện hồ sơ",
        description: "Thêm ảnh đại diện và giới thiệu bản thân để người khác dễ nhận ra bạn.",
        cta: "Cập nhật hồ sơ",
      },
    },
  },
  en: {
    view: {
      title: "My profile",
      subtitle: "Only you see this page — update whenever you want.",
      edit: "Edit profile",
      noBio: "No bio yet.",
      noLocation: "No location.",
      roles: {
        [UserRole.CONSUMER]: "Consumer",
        [UserRole.SELLER]: "Individual seller",
        [UserRole.COOPERATIVE]: "Cooperative",
        [UserRole.ENTERPRISE]: "Enterprise",
        [UserRole.EXPERT]: "Expert",
        [UserRole.ADMIN]: "Admin",
        [UserRole.GUEST]: "Guest",
      },
      loading: "Loading profile...",
      loadError: "Could not load profile.",
    },
    screen: {
      postsTab: "Posts",
      postsTitle: "Your posts",
      postsSubtitle: "Share season updates and harvest news",
      introTitle: "Intro",
      vgxTitle: "VietGreenX",
      statPosts: "posts",
      statFollowers: "followers",
      statFollowing: "following",
      shortcutMarketplace: "Marketplace",
      shortcutGreenProfile: "Green profile",
      photosTitle: "Photos",
      viewAllPhotos: "See all photos",
      noPhotos: "No photos yet",
      transactionHistory: {
        title: "Transaction & Connection History",
        subtitle: "Quotations and commercial connections between parties",
        sent: "Sent",
        received: "Received",
        statusPending: "Pending",
        statusAccepted: "Accepted",
        statusRejected: "Rejected",
        statusExpired: "Expired",
        statusWithdrawn: "Withdrawn",
        emptyTitle: "No transaction history",
        emptyDescription: "No transactions or quotation connections recorded yet.",
        productLabel: "Product",
        quantityLabel: "Quantity",
        partnerLabel: "Partner",
        dateLabel: "Date",
      },
    },
    edit: {
      title: "Edit profile",
      subtitle: "Update your public profile details.",
      changeAvatar: "Change avatar",
      avatarUploading: "Uploading...",
      avatarHint: "PNG, JPG, or WebP, up to 5MB.",
      avatarSaved: "Avatar updated.",
      avatarSaveError: "Could not upload avatar.",
      avatarInvalidType: "Only PNG, JPG, or WebP is supported.",
      avatarTooLarge: "Image must be 5MB or smaller.",
      displayName: "Display name",
      bio: "Bio",
      bioHint: "Up to 500 characters",
      website: "Website",
      websitePlaceholder: "https://...",
      address: {
        locationTitle: "Location",
        province: "Province / City",
        ward: "Ward / Commune",
        provincePlaceholder: "Select province / city",
        wardPlaceholder: "Select ward / commune",
        searchPlaceholder: "Search...",
        emptyText: "No results.",
        loading: "Loading locations...",
        loadError: "Could not load locations. Please try again later.",
        mergerNotice: "Based on the post-2025 administrative merger (34 provinces and cities).",
        legacyHint: "Saved location is no longer in the list — re-select to update.",
      },
      save: "Save changes",
      saved: "Profile updated.",
      saveError: "Could not save profile.",
      back: "Back to profile",
    },
    banner: {
      dismiss: "Dismiss suggestion",
      greenProfile: {
        title: "Start selling",
        description:
          "Create a Green Profile to list products, manage seasons, and generate traceability QR codes.",
        cta: "Create Green Profile",
      },
      orgSetup: {
        title: "Set up your organization",
        description:
          "Create an organization profile to unlock member management, B2B trade, and batch traceability.",
        cta: "Set up now",
      },
      profileCompletion: {
        title: "Complete your profile",
        description: "Add an avatar and bio so others can recognize you.",
        cta: "Update profile",
      },
    },
  },
} as const;

export function getProfileCopy(locale: AppLocale) {
  return PROFILE_COPY[locale] ?? PROFILE_COPY.vi;
}
