import type { AppLocale } from "@/shared/i18n/locale";

export type ChatFilterTab = "all" | "unread" | "important";

const CHAT_COPY = {
  vi: {
    inbox: {
      title: "Hộp thư",
      searchPlaceholder: "Tìm kiếm cuộc trò chuyện...",
      selectConversation: "Chọn một cuộc trò chuyện",
      startChat: "hoặc bắt đầu nhắn tin trao đổi nông sản xanh với đối tác",
      noConversations: "Chưa có cuộc trò chuyện nào",
      noFilterMatch: "Không tìm thấy hội thoại phù hợp",
      newChat: "Tạo hội thoại mới",
      loading: "Đang tải hộp thư...",
      defaultUser: "Người dùng",
      tabs: {
        all: "Tất cả",
        unread: "Chưa đọc",
        important: "Quan trọng",
      },
    },
    conversation: {
      activeStatus: "Đang hoạt động",
      offlineStatus: "Ngoại tuyến",
      today: "Hôm nay",
      yesterday: "Hôm qua",
      unreadDivider: "Tin và nhận chưa đọc",
      inputPlaceholder: "Nhập tin...",
      send: "Gửi",
      noMessages: "Chưa có tin nhắn nào. Hãy bắt đầu trao đổi ngay!",
      loading: "Đang tải tin nhắn...",
      defaultProductPrice: "35.000đ/kg",
      preview: {
        youPrefix: "Bạn: ",
        sentImage: "Đã gửi một hình ảnh",
        sentProduct: "Đã gửi một sản phẩm",
        noMessages: "Chưa có tin nhắn",
      },
      attachments: {
        image: "Gửi ảnh",
        file: "Tập tin",
        product: "Thẻ sản phẩm",
      },
    },
    sidebar: {
      viewProfile: "Xem Hồ Sơ",
      generalInfo: "Thông tin chung",
      joined: "Tham gia:",
      phone: "Số điện thoại:",
      email: "Email:",
      address: "Địa chỉ:",
      bio: "Mô tả:",
      noData: "—",
      options: "Tùy chọn",
      notifications: "Thông báo",
      searchMessages: "Tìm kiếm cuộc trò chuyện",
      mediaFiles: "Ảnh, video, tập tin đã gửi",
      report: "Báo cáo cuộc trò chuyện",
      deleteChat: "Xóa cuộc trò chuyện",
      confirmDelete: "Bạn có chắc chắn muốn xóa lịch sử cuộc trò chuyện này?",
      exchangedProducts: "Sản phẩm đã trao đổi",
    },
    modal: {
      title: "Tạo hội thoại mới",
      labelUuid: "ID Người dùng hoặc Đối tác",
      placeholderUuid: "Nhập UUID người dùng cần nhắn tin...",
      suggestedPartners: "Đối tác gợi ý (Chọn nhanh):",
      cancel: "Hủy",
      submit: "Bắt đầu nhắn tin",
      submitting: "Đang tạo...",
      demoPartners: [],
    },
    errors: {
      createFailed: "Không thể tạo cuộc trò chuyện",
      sendFailed: "Không thể gửi tin nhắn",
    },
  },
  en: {
    inbox: {
      title: "Inbox",
      searchPlaceholder: "Search conversations...",
      selectConversation: "Select a conversation",
      startChat: "or start messaging green agricultural partners",
      noConversations: "No conversations yet",
      noFilterMatch: "No matching conversations found",
      newChat: "New conversation",
      loading: "Loading inbox...",
      defaultUser: "User",
      tabs: {
        all: "All",
        unread: "Unread",
        important: "Important",
      },
    },
    conversation: {
      activeStatus: "Active now",
      offlineStatus: "Offline",
      today: "Today",
      yesterday: "Yesterday",
      unreadDivider: "Unread messages",
      inputPlaceholder: "Type a message...",
      send: "Send",
      noMessages: "No messages yet. Start conversation now!",
      loading: "Loading messages...",
      defaultProductPrice: "35.000đ/kg",
      preview: {
        youPrefix: "You: ",
        sentImage: "Sent an image",
        sentProduct: "Sent a product",
        noMessages: "No messages yet",
      },
      attachments: {
        image: "Send photo",
        file: "Attachment",
        product: "Product card",
      },
    },
    sidebar: {
      viewProfile: "View Profile",
      generalInfo: "General Info",
      joined: "Joined:",
      phone: "Phone:",
      email: "Email:",
      address: "Address:",
      bio: "Bio:",
      noData: "—",
      options: "Options",
      notifications: "Notifications",
      searchMessages: "Search messages",
      mediaFiles: "Shared media and files",
      report: "Report conversation",
      deleteChat: "Delete conversation",
      confirmDelete: "Are you sure you want to delete this conversation history?",
      exchangedProducts: "Exchanged Products",
    },
    modal: {
      title: "New Conversation",
      labelUuid: "User ID or Partner ID",
      placeholderUuid: "Enter UUID of user to message...",
      suggestedPartners: "Suggested Partners (Quick Select):",
      cancel: "Cancel",
      submit: "Start messaging",
      submitting: "Creating...",
      demoPartners: [],
    },
    errors: {
      createFailed: "Unable to create conversation",
      sendFailed: "Unable to send message",
    },
  },
} as const;

export function getChatCopy(locale: AppLocale) {
  return CHAT_COPY[locale] ?? CHAT_COPY.vi;
}
