import type { AppLocale } from "@/shared/i18n/locale";

const ACCOUNT_VALIDATION_COPY = {
  vi: {
    currentPasswordRequired: "Vui lòng nhập mật khẩu hiện tại",
    verifyPasswordRequired: "Vui lòng xác nhận mật khẩu mới",
    deletePasswordRequired: "Vui lòng nhập mật khẩu để xác nhận",
    passwordMismatch: "Mật khẩu xác nhận không khớp",
    otpLength: "OTP phải có 6 số",
    emailInvalid: "Email không hợp lệ",
    phoneRequired: "Vui lòng nhập số điện thoại",
    phoneInvalid: "Số điện thoại không hợp lệ",
  },
  en: {
    currentPasswordRequired: "Please enter your current password",
    verifyPasswordRequired: "Please confirm your new password",
    deletePasswordRequired: "Please enter your password to confirm",
    passwordMismatch: "Confirmation password does not match",
    otpLength: "OTP must be 6 digits",
    emailInvalid: "Invalid email address",
    phoneRequired: "Please enter a phone number",
    phoneInvalid: "Invalid phone number",
  },
} as const;

export function getAccountValidationCopy(locale: AppLocale) {
  return ACCOUNT_VALIDATION_COPY[locale] ?? ACCOUNT_VALIDATION_COPY.vi;
}

const ACCOUNT_COPY = {
  vi: {
    title: "Cài đặt tài khoản",
    subtitle: "Bảo mật, dữ liệu cá nhân và phiên đăng nhập.",
    contact: {
      title: "Liên hệ & đăng nhập",
      description: "Email, số điện thoại và mật khẩu dùng để đăng nhập.",
      loading: "Đang tải…",
      loadError: "Không tải được thông tin liên hệ.",
      emailLabel: "Email",
      phoneLabel: "Số điện thoại",
      passwordLabel: "Mật khẩu",
      passwordMasked: "••••••••",
      notLinked: "Chưa liên kết",
      unverified: "Chưa xác minh",
      addEmail: "Thêm email",
      changeEmail: "Đổi email",
      addPhone: "Thêm SĐT",
      changePhone: "Đổi SĐT",
      changePassword: "Đổi mật khẩu",
    },
    export: {
      title: "Xuất dữ liệu cá nhân",
      description: "Tải bản sao thông tin tài khoản theo quy định bảo mật.",
      action: "Xuất dữ liệu",
      loading: "Đang chuẩn bị…",
      success: "Đã tải dữ liệu cá nhân.",
      error: "Không thể xuất dữ liệu.",
    },
    password: {
      title: "Đổi mật khẩu",
      description: "Xác minh OTP qua email hoặc SĐT đã đăng ký.",
      action: "Đổi mật khẩu",
      dialogTitle: "Đổi mật khẩu",
      step1Description: "Nhập mật khẩu hiện tại và chọn kênh nhận OTP.",
      step2Description: "Nhập mật khẩu mới và mã OTP.",
      noOtpChannel: "Tài khoản chưa có email hoặc SĐT để nhận OTP.",
      channels: { email: "Email", phone: "Số điện thoại" },
      sendOtp: "Gửi mã OTP",
      currentPassword: "Mật khẩu hiện tại",
      newPassword: "Mật khẩu mới",
      confirmPassword: "Xác nhận mật khẩu mới",
      passwordHint: "Tối thiểu 8 ký tự, có chữ và số",
      otp: "Mã OTP",
      submit: "Đổi mật khẩu",
      success: "Đã đổi mật khẩu. Vui lòng đăng nhập lại.",
      back: "Quay lại",
      resend: "Gửi lại OTP",
      resendWait: "Gửi lại sau {s}s",
      devOtpHint: "Mã OTP (dev):",
    },
    email: {
      title: "Đổi email",
      description: "OTP sẽ gửi tới email mới sau khi xác minh mật khẩu.",
      action: "Đổi email",
      addDialogTitle: "Thêm email",
      changeDialogTitle: "Đổi email",
      dialogTitle: "Đổi email",
      step1Description: "Nhập mật khẩu và email mới.",
      step2Description: "Nhập mã OTP gửi tới email mới.",
      newEmail: "Email mới",
      sendOtp: "Gửi mã OTP",
      otp: "Mã OTP",
      submit: "Xác nhận đổi email",
      success: "Đã đổi email. Vui lòng đăng nhập lại.",
      back: "Quay lại",
      resend: "Gửi lại OTP",
      resendWait: "Gửi lại sau {s}s",
      devOtpHint: "Mã OTP (dev):",
    },
    phone: {
      title: "Đổi số điện thoại",
      description: "OTP sẽ gửi tới số mới sau khi xác minh mật khẩu.",
      action: "Đổi SĐT",
      addDialogTitle: "Thêm số điện thoại",
      changeDialogTitle: "Đổi số điện thoại",
      dialogTitle: "Đổi số điện thoại",
      step1Description: "Nhập mật khẩu và số điện thoại mới.",
      step2Description: "Nhập mã OTP gửi tới số mới.",
      newPhone: "Số điện thoại mới",
      sendOtp: "Gửi mã OTP",
      otp: "Mã OTP",
      submit: "Xác nhận đổi SĐT",
      success: "Đã đổi số điện thoại. Vui lòng đăng nhập lại.",
      back: "Quay lại",
      resend: "Gửi lại OTP",
      resendWait: "Gửi lại sau {s}s",
      devOtpHint: "Mã OTP (dev):",
    },
    delete: {
      title: "Xóa tài khoản",
      description: "Hành động này vô hiệu hóa tài khoản và đăng xuất mọi thiết bị.",
      action: "Xóa tài khoản",
      dialogTitle: "Xác nhận xóa tài khoản",
      dialogDescription: "Nhập mật khẩu để xác nhận. Dữ liệu sẽ được ẩn theo chính sách bảo mật.",
      passwordLabel: "Mật khẩu hiện tại",
      cancel: "Huỷ",
      confirm: "Xóa tài khoản",
      deleting: "Đang xóa…",
      success: "Đã xóa tài khoản.",
    },
    errors: {
      generic: "Đã có lỗi xảy ra. Vui lòng thử lại.",
      incorrectPassword: "Mật khẩu hiện tại không đúng.",
      emailNotFound: "Tài khoản chưa có email đăng ký.",
      phoneNotFound: "Tài khoản chưa có số điện thoại đăng ký.",
      passwordMismatch: "Mật khẩu xác nhận không khớp.",
      otpIncorrect: "Mã OTP không đúng.",
      otpExpired: "Mã OTP đã hết hạn, vui lòng yêu cầu mã mới.",
      passwordReused: "Không được dùng lại 3 mật khẩu gần nhất.",
      cooldown60s: "Vui lòng đợi 60 giây trước khi gửi lại.",
      rateLimited: "Quá nhiều lần thử. Vui lòng thử lại sau.",
      emailExists: "Email đã được sử dụng.",
      phoneExists: "Số điện thoại đã được sử dụng.",
    },
  },
  en: {
    title: "Account settings",
    subtitle: "Security, personal data, and sessions.",
    contact: {
      title: "Contact & sign-in",
      description: "Email, phone, and password used to sign in.",
      loading: "Loading…",
      loadError: "Could not load contact info.",
      emailLabel: "Email",
      phoneLabel: "Phone",
      passwordLabel: "Password",
      passwordMasked: "••••••••",
      notLinked: "Not linked",
      unverified: "Not verified",
      addEmail: "Add email",
      changeEmail: "Change email",
      addPhone: "Add phone",
      changePhone: "Change phone",
      changePassword: "Change password",
    },
    export: {
      title: "Export personal data",
      description: "Download a copy of your account information.",
      action: "Export data",
      loading: "Preparing…",
      success: "Personal data downloaded.",
      error: "Could not export data.",
    },
    password: {
      title: "Change password",
      description: "Verify via OTP sent to your registered email or phone.",
      action: "Change password",
      dialogTitle: "Change password",
      step1Description: "Enter your current password and choose an OTP channel.",
      step2Description: "Enter your new password and OTP code.",
      noOtpChannel: "No email or phone on this account to receive an OTP.",
      channels: { email: "Email", phone: "Phone" },
      sendOtp: "Send OTP",
      currentPassword: "Current password",
      newPassword: "New password",
      confirmPassword: "Confirm new password",
      passwordHint: "At least 8 characters with letters and numbers",
      otp: "OTP code",
      submit: "Change password",
      success: "Password changed. Please log in again.",
      back: "Back",
      resend: "Resend OTP",
      resendWait: "Resend in {s}s",
      devOtpHint: "OTP code (dev):",
    },
    email: {
      title: "Change email",
      description: "An OTP will be sent to your new email after password verification.",
      action: "Change email",
      addDialogTitle: "Add email",
      changeDialogTitle: "Change email",
      dialogTitle: "Change email",
      step1Description: "Enter your password and new email.",
      step2Description: "Enter the OTP sent to your new email.",
      newEmail: "New email",
      sendOtp: "Send OTP",
      otp: "OTP code",
      submit: "Confirm email change",
      success: "Email changed. Please log in again.",
      back: "Back",
      resend: "Resend OTP",
      resendWait: "Resend in {s}s",
      devOtpHint: "OTP code (dev):",
    },
    phone: {
      title: "Change phone",
      description: "An OTP will be sent to your new number after password verification.",
      action: "Change phone",
      addDialogTitle: "Add phone number",
      changeDialogTitle: "Change phone number",
      dialogTitle: "Change phone number",
      step1Description: "Enter your password and new phone number.",
      step2Description: "Enter the OTP sent to your new number.",
      newPhone: "New phone number",
      sendOtp: "Send OTP",
      otp: "OTP code",
      submit: "Confirm phone change",
      success: "Phone number changed. Please log in again.",
      back: "Back",
      resend: "Resend OTP",
      resendWait: "Resend in {s}s",
      devOtpHint: "OTP code (dev):",
    },
    delete: {
      title: "Delete account",
      description: "This deactivates your account and signs out all devices.",
      action: "Delete account",
      dialogTitle: "Confirm account deletion",
      dialogDescription: "Enter your password to confirm. Data will be hidden per our privacy policy.",
      passwordLabel: "Current password",
      cancel: "Cancel",
      confirm: "Delete account",
      deleting: "Deleting…",
      success: "Account deleted.",
    },
    errors: {
      generic: "Something went wrong. Please try again.",
      incorrectPassword: "Current password is incorrect.",
      emailNotFound: "No email is registered on this account.",
      phoneNotFound: "No phone number is registered on this account.",
      passwordMismatch: "Confirmation password does not match.",
      otpIncorrect: "Incorrect OTP.",
      otpExpired: "OTP has expired, please request a new one.",
      passwordReused: "Cannot reuse your last 3 passwords.",
      cooldown60s: "Please wait 60 seconds before resending.",
      rateLimited: "Too many attempts. Please try again later.",
      emailExists: "This email is already in use.",
      phoneExists: "This phone number is already in use.",
    },
  },
} as const;

export function getAccountCopy(locale: AppLocale) {
  return ACCOUNT_COPY[locale] ?? ACCOUNT_COPY.vi;
}
