import type { AppLocale } from "@/shared/i18n/locale";

export const GREEN_PROFILE_PHOTO_MAX = 20;
export const GREEN_PROFILE_VIDEO_MAX = 3;
export const GREEN_PROFILE_PHOTO_ACCEPT = "image/png,image/jpeg,image/webp";
export const GREEN_PROFILE_VIDEO_ACCEPT = "video/mp4,video/quicktime,video/webm,video/x-msvideo";
export const GREEN_PROFILE_PHOTO_MAX_BYTES = 5 * 1024 * 1024;
export const GREEN_PROFILE_VIDEO_MAX_BYTES = 5 * 1024 * 1024;

const GREEN_PROFILE_VALIDATION_COPY = {
  vi: {
    profileNameRequired: "Vui lòng nhập tên hồ sơ xanh",
    provinceRequired: "Vui lòng chọn tỉnh/thành",
    farmAreaPositive: "Diện tích phải lớn hơn 0",
    yieldPositive: "Sản lượng phải lớn hơn 0",
    latInvalid: "Vĩ độ phải từ -90 đến 90",
    lngInvalid: "Kinh độ phải từ -180 đến 180",
    photoInvalidType: "Ảnh phải là PNG, JPEG hoặc WebP",
    photoTooLarge: "Ảnh không được vượt quá 5MB",
    videoInvalidType: "Video phải là MP4, MOV, WebM hoặc AVI",
    videoTooLarge: "Video không được vượt quá 5MB",
    photoLimit: "Tối đa 20 ảnh",
    videoLimit: "Tối đa 3 video",
  },
  en: {
    profileNameRequired: "Please enter a green profile name",
    provinceRequired: "Please select a province",
    farmAreaPositive: "Area must be greater than 0",
    yieldPositive: "Yield must be greater than 0",
    latInvalid: "Latitude must be between -90 and 90",
    lngInvalid: "Longitude must be between -180 and 180",
    photoInvalidType: "Photo must be PNG, JPEG, or WebP",
    photoTooLarge: "Photo must be 5MB or smaller",
    videoInvalidType: "Video must be MP4, MOV, WebM, or AVI",
    videoTooLarge: "Video must be 5MB or smaller",
    photoLimit: "Up to 20 photos",
    videoLimit: "Up to 3 videos",
  },
} as const;

export function getGreenProfileValidationCopy(locale: AppLocale) {
  return GREEN_PROFILE_VALIDATION_COPY[locale] ?? GREEN_PROFILE_VALIDATION_COPY.vi;
}

const GREEN_PROFILE_COPY = {
  vi: {
    hub: {
      createCta: "Tạo hồ sơ xanh",
      emptyTitle: "Chưa có hồ sơ xanh",
      emptyDescription:
        "Tạo hồ sơ trang trại để ghi nhật ký canh tác, quản lý mùa vụ và chuẩn bị truy xuất QR.",
      loadError: "Không thể tải danh sách hồ sơ xanh.",
      loading: "Đang tải...",
      areaHa: "ha",
      published: "Đã xuất bản",
      draft: "Bản nháp",
      certified: "Đã chứng nhận",
      notCertified: "Chưa chứng nhận",
      certLabels: {
        vietgap: "VietGAP",
        organic: "Hữu cơ",
      },
      reviewCount: (count: number) => `${count} đánh giá`,
      statsPanel: {
        mainProducts: "Sản phẩm chủ lực",
        area: "Diện tích",
        cultivationZone: "Vùng canh tác",
        yield: "Sản lượng",
        yieldEstimate: "Ước tính",
        certifications: "Chứng nhận",
        growingZone: "Mã vùng trồng",
        cleanOrganic: "Rau sạch, hữu cơ",
        notUpdated: "Chưa cập nhật",
        ha: "ha",
        tonnesPerYear: "tấn/năm",
      },
      actions: {
        edit: "Chỉnh sửa",
        seasons: "Mùa vụ",
        log: "Nhật ký",
        publish: "Xuất bản",
        unpublish: "Ẩn hồ sơ",
        publishing: "Đang xử lý…",
      },
      toast: {
        createSuccess: "Đã tạo hồ sơ xanh.",
        createError: "Không thể tạo hồ sơ xanh. Vui lòng thử lại.",
        updateSuccess: "Đã cập nhật hồ sơ xanh.",
        updateError: "Không thể cập nhật hồ sơ xanh.",
        publishSuccess: "Đã xuất bản hồ sơ xanh.",
        unpublishSuccess: "Đã ẩn hồ sơ xanh.",
        publishError: "Không thể thay đổi trạng thái xuất bản.",
      },
      rail: {
        title: "Hồ sơ xanh",
        contextTitle: "Điều hướng nhanh",
        contextDescription: "Chuyển giữa chỉnh sửa, mùa vụ và nhật ký sản xuất.",
      },
      view: {
        verified: "Đã xác minh",
        memberSince: (month: string, year: number) => `Thành viên từ ${month}/${year}`,
        growingZoneLabel: "Vùng sản xuất",
        editProfile: "Chỉnh sửa hồ sơ",
        viewStats: "Xem thống kê",
        notUpdated: "Chưa cập nhật",
        stats: {
          mainProducts: "Sản phẩm chủ lực",
          area: "Diện tích",
          cultivationZone: "Vùng canh tác",
          yield: "Sản lượng",
          yieldUnit: "t/năm",
          yieldEstimate: "Ước tính",
          certifications: "Chứng nhận",
          growingZone: "Mã vùng trồng",
        },
        photos: {
          title: "Hình ảnh thực tế",
          viewAll: "Xem tất cả",
          empty: "Chưa có ảnh trang trại",
        },
        videos: {
          title: "Video giới thiệu",
          count: (n: number) => `${n} video`,
          empty: "Chưa có video",
          introLabel: "Giới thiệu mô hình canh tác",
          videoLabel: (n: number) => `Video #${n}`,
        },
        rating: {
          title: "Đánh giá uy tín",
          count: (n: number) => `${n} đánh giá`,
          empty: "Chưa có đánh giá",
        },
        transactions: {
          tab: "Lịch sử giao dịch",
          connections: "Kết nối",
          export: "Xuất báo cáo",
          underDevelopment: "Chức năng lịch sử giao dịch đang được phát triển.",
          connectionsUnderDevelopment: "Tính năng kết nối đang được phát triển.",
          showing: (n: number) => `Hiển thị ${n} giao dịch`,
          columns: {
            stt: "STT",
            date: "Ngày giao dịch",
            partner: "Đối tác",
            product: "Sản phẩm",
            qty: "Số lượng",
            value: "Giá trị",
            status: "Trạng thái",
          },
        },
      },
    },
    form: {
      createTitle: "Tạo hồ sơ xanh",
      editTitle: "Chỉnh sửa hồ sơ xanh",
      createSubtitle: "Thông tin trang trại hiển thị công khai và phục vụ truy xuất.",
      editSubtitle: "Cập nhật thông tin trang trại.",
      sections: {
        basic: "Thông tin cơ bản",
        location: "Vị trí sản xuất",
        production: "Thông tin sản xuất",
        coordinates: "Tọa độ GPS (tùy chọn)",
        certification: "Chứng nhận",
        media: "Hình ảnh & video",
      },
      fields: {
        profileName: "Tên hồ sơ xanh / vùng sản xuất",
        province: "Tỉnh / thành phố",
        ward: "Phường / Xã",
        addressDetail: "Địa chỉ chi tiết",
        growingZoneCode: "Vùng sinh thái",
        area: "Diện tích (ha)",
        annualYield: "Sản lượng hàng năm (tấn)",
        latitude: "Vĩ độ",
        longitude: "Kinh độ",
        description: "Mô tả",
        productionProcess: "Quy trình sản xuất",
      },
      emptyText: "Không tìm thấy dữ liệu",
      selectPlaceholder: (field: string) => `Chọn ${field.toLowerCase()}...`,
      searchPlaceholder: (field: string) => `Tìm ${field.toLowerCase()}...`,
      save: "Lưu hồ sơ",
      cancel: "Huỷ",
      media: {
        avatarTitle: "Ảnh đại diện",
        avatarHint: "Hiển thị trên hồ sơ (PNG, JPEG, WebP - tối đa 5MB)",
        photosTitle: "Ảnh trang trại",
        videosTitle: "Video trang trại",
        addPhoto: "Thêm ảnh",
        addVideo: "Thêm video",
        photoHint: "PNG, JPEG hoặc WebP — tối đa 5MB mỗi ảnh",
        videoHint: "MP4, MOV, WebM hoặc AVI — tối đa 5MB mỗi video",
        remove: "Xóa",
        uploading: "Đang tải lên…",
        uploadError: "Không thể tải lên tệp.",
        savedMedia: "Đã lưu",
        viewVideo: "Xem video",
      },
    },
    nav: {
      breadcrumb: "Hồ sơ xanh",
      edit: "Chỉnh sửa",
      seasons: "Mùa vụ",
      log: "Nhật ký",
    },
    seasons: {
      title: "Quản lý mùa vụ",
      subtitle: "Theo dõi từng vụ canh tác gắn với hồ sơ xanh.",
      addCta: "Thêm mùa vụ",
      emptyTitle: "Chưa có mùa vụ",
      emptyDescription: "Thêm mùa vụ để ghi nhật ký canh tác theo từng vụ.",
      columns: {
        name: "Tên mùa vụ",
        start: "Bắt đầu",
        harvest: "Thu hoạch dự kiến",
        status: "Trạng thái",
      },
      loadError: "Không thể tải danh sách mùa vụ.",
      noGreenProfile: "Cần tạo hồ sơ xanh trước khi quản lý mùa vụ.",
      status: {
        planning: "Lên kế hoạch",
        active: "Đang canh tác",
        harvested: "Đã thu hoạch",
        cancelled: "Đã huỷ",
      },
    },
    log: {
      title: "Nhật ký sản xuất",
      subtitle: "Ghi chép bất biến — không sửa hoặc xóa sau khi lưu.",
      addCta: "Ghi nhật ký",
      emptyTitle: "Chưa có nhật ký",
      emptyDescription: "Ghi lại gieo hạt, chăm sóc, thu hoạch để minh bạch quy trình sản xuất.",
      appendOnlyNote: "Nhật ký chỉ thêm mới, phục vụ truy xuất nguồn gốc.",
      filterAllSeasons: "Tất cả mùa vụ",
      loadError: "Không thể tải nhật ký sản xuất.",
    },
  },
  en: {
    hub: {
      createCta: "Create green profile",
      emptyTitle: "No green profile yet",
      emptyDescription:
        "Create a farm profile to log cultivation, manage seasons, and prepare QR traceability.",
      loadError: "Could not load green profiles.",
      loading: "Loading...",
      areaHa: "ha",
      published: "Published",
      draft: "Draft",
      certified: "Certified",
      notCertified: "Not certified",
      certLabels: {
        vietgap: "VietGAP",
        organic: "Organic",
      },
      reviewCount: (count: number) => `${count} reviews`,
      statsPanel: {
        mainProducts: "Main products",
        area: "Area",
        cultivationZone: "Cultivation zone",
        yield: "Yield",
        yieldEstimate: "Estimate",
        certifications: "Certifications",
        growingZone: "Growing zone code",
        cleanOrganic: "Clean, organic",
        notUpdated: "Not updated",
        ha: "ha",
        tonnesPerYear: "t/year",
      },
      actions: {
        edit: "Edit",
        seasons: "Seasons",
        log: "Production log",
        publish: "Publish",
        unpublish: "Unpublish",
        publishing: "Updating…",
      },
      toast: {
        createSuccess: "Green profile created.",
        createError: "Could not create green profile. Please try again.",
        updateSuccess: "Green profile updated.",
        updateError: "Could not update green profile.",
        publishSuccess: "Green profile published.",
        unpublishSuccess: "Green profile unpublished.",
        publishError: "Could not change publish status.",
      },
      rail: {
        title: "Green profile",
        contextTitle: "Quick navigation",
        contextDescription: "Switch between edit, seasons, and production log.",
      },
      view: {
        verified: "Verified",
        memberSince: (month: string, year: number) => `Member since ${month}/${year}`,
        growingZoneLabel: "Growing zone",
        editProfile: "Edit profile",
        viewStats: "View analytics",
        notUpdated: "Not updated",
        stats: {
          mainProducts: "Main products",
          area: "Farm area",
          cultivationZone: "Cultivation zone",
          yield: "Annual yield",
          yieldUnit: "t/year",
          yieldEstimate: "Estimated",
          certifications: "Certifications",
          growingZone: "Growing zone code",
        },
        photos: {
          title: "Farm photos",
          viewAll: "View all",
          empty: "No farm photos yet",
        },
        videos: {
          title: "Introduction video",
          count: (n: number) => `${n} video${n !== 1 ? "s" : ""}`,
          empty: "No videos yet",
          introLabel: "Farm model introduction",
          videoLabel: (n: number) => `Video #${n}`,
        },
        rating: {
          title: "Credibility rating",
          count: (n: number) => `${n} review${n !== 1 ? "s" : ""}`,
          empty: "No reviews yet",
        },
        transactions: {
          tab: "Transaction history",
          connections: "Connections",
          export: "Export report",
          underDevelopment: "Transaction history feature is under development.",
          connectionsUnderDevelopment: "Connections feature is under development.",
          showing: (n: number) => `Showing ${n} transactions`,
          columns: {
            stt: "#",
            date: "Transaction date",
            partner: "Partner",
            product: "Product",
            qty: "Quantity",
            value: "Value",
            status: "Status",
          },
        },
      },
    },
    form: {
      createTitle: "Create green profile",
      editTitle: "Edit green profile",
      createSubtitle: "Farm info shown publicly and used for traceability.",
      editSubtitle: "Update farm information.",
      sections: {
        basic: "Basic information",
        location: "Production location",
        production: "Production details",
        coordinates: "GPS coordinates (optional)",
        certification: "Certifications",
        media: "Photos & video",
      },
      fields: {
        profileName: "Farm / production area name",
        province: "Province",
        ward: "Ward / Commune",
        addressDetail: "Address detail",
        growingZoneCode: "Growing zone",
        area: "Farm area (ha)",
        annualYield: "Annual yield (tonnes)",
        latitude: "Latitude",
        longitude: "Longitude",
        description: "Description",
        productionProcess: "Production process",
      },
      emptyText: "No data found",
      selectPlaceholder: (field: string) => `Select ${field.toLowerCase()}...`,
      searchPlaceholder: (field: string) => `Search ${field.toLowerCase()}...`,
      save: "Save profile",
      cancel: "Cancel",
      media: {
        avatarTitle: "Avatar",
        avatarHint: "Shown on profile (PNG, JPEG, WebP - max 5MB)",
        photosTitle: "Farm photos",
        videosTitle: "Farm videos",
        addPhoto: "Add photo",
        addVideo: "Add video",
        photoHint: "PNG, JPEG, or WebP — up to 5MB each",
        videoHint: "MP4, MOV, WebM, or AVI — up to 5MB each",
        remove: "Remove",
        uploading: "Uploading…",
        uploadError: "Could not upload file.",
        savedMedia: "Saved",
        viewVideo: "View video",
      },
    },
    nav: {
      breadcrumb: "Green profile",
      edit: "Edit",
      seasons: "Seasons",
      log: "Production log",
    },
    seasons: {
      title: "Crop seasons",
      subtitle: "Track cultivation cycles for this green profile.",
      addCta: "Add season",
      emptyTitle: "No seasons yet",
      emptyDescription: "Add a season to organize production logs by cycle.",
      columns: {
        name: "Season name",
        start: "Start",
        harvest: "Expected harvest",
        status: "Status",
      },
      loadError: "Could not load crop seasons.",
      noGreenProfile: "Create a green profile before managing crop seasons.",
      status: {
        planning: "Planning",
        active: "Active",
        harvested: "Harvested",
        cancelled: "Cancelled",
      },
    },
    log: {
      title: "Production log",
      subtitle: "Immutable records — no edit or delete after save.",
      addCta: "Add log entry",
      emptyTitle: "No log entries yet",
      emptyDescription: "Record sowing, care, and harvest for transparent traceability.",
      appendOnlyNote: "Append-only log for origin traceability.",
      filterAllSeasons: "All seasons",
      loadError: "Could not load production logs.",
    },
  },
} as const;

export function getGreenProfileCopy(locale: AppLocale) {
  return GREEN_PROFILE_COPY[locale] ?? GREEN_PROFILE_COPY.vi;
}

export type GreenProfileCopy = ReturnType<typeof getGreenProfileCopy>;
