import type { AppLocale } from "@/shared/i18n/locale";
import { ROUTES } from "@/shared/routing";

const POSTS_VALIDATION_COPY = {
  vi: {
    bodyMax: "Tối đa 2000 ký tự",
    bodyOrMediaRequired: "Nhập nội dung hoặc chọn ảnh.",
  },
  en: {
    bodyMax: "Maximum 2000 characters",
    bodyOrMediaRequired: "Add text or choose a photo.",
  },
} as const;

export function getPostsValidationCopy(locale: AppLocale) {
  return POSTS_VALIDATION_COPY[locale] ?? POSTS_VALIDATION_COPY.vi;
}

const POSTS_COPY = {
  vi: {
    composer: {
      title: "Chia sẻ với cộng đồng",
      placeholder: "Bạn đang nghĩ gì về nông sản xanh hôm nay?",
      photo: "Ảnh/Video",
      greenProfile: "Sản phẩm",
      marketplace: "QR truy xuất",
      submit: "Đăng",
      submitting: "Đang đăng...",
      cancel: "Hủy",
      empty: "Nhập nội dung hoặc chọn ảnh.",
      imageInvalidType: "Chỉ hỗ trợ PNG, JPG hoặc WebP.",
      imageTooLarge: "Ảnh tối đa 5MB.",
      removeImage: "Xóa ảnh",
      contentCategory: "Loại bài",
      contentCategoryPlaceholder: "Chọn loại bài (tuỳ chọn)",
      contentCategoryNone: "Không chọn loại",
      more: "Thêm",
      moreOptions: "Tùy chọn bài viết",
    },
    tags: {
      title: "Gắn nhãn cho bài",
      hint: "Giúp người đọc biết sản phẩm, vùng miền và danh mục liên quan.",
      listAria: "Nhãn bài viết",
      metaAria: "Ngữ cảnh bài viết",
      remove: "Gỡ nhãn",
      region: "Vùng",
      catalogCategory: "Danh mục",
      product: "Sản phẩm",
      productSearch: "Tìm sản phẩm...",
      productEmpty: "Chưa có sản phẩm.",
      maxReached: "Tối đa 20 nhãn / bài.",
      regionPlaceholder: "Chọn tỉnh / vùng",
      regionSearch: "Tìm tỉnh, thành...",
      regionEmpty: "Không thấy khu vực.",
      categoryPlaceholder: "Chọn danh mục",
      categorySearch: "Tìm danh mục...",
      categoryEmpty: "Không thấy danh mục.",
      types: {
        region: "Khu vực",
        category: "Danh mục",
        product: "Sản phẩm",
      },
    },
    hashtags: {
      useCustom: (tag: string) => `Tạo #${tag}`,
      searchError: "Không tải được gợi ý hashtag. Bạn vẫn có thể gõ #tag thủ công.",
      postCount: (count: number) => `${count} bài`,
      limitExceeded: "Tối đa 30 hashtag trong nội dung bài.",
      exploreComingSoon: "Xem bài theo hashtag sẽ có sớm.",
    },
    postContentCategory: {
      produce_story: "Câu chuyện nông sản",
      crop_journal: "Nhật ký mùa vụ",
      farming_technique: "Kỹ thuật canh tác",
      market_price: "Giá thị trường",
      trade_connection: "Kết nối thương mại",
      ocop_vietgap_story: "OCOP / VietGAP",
    },
    stories: {
      ariaLabel: "Tin nổi bật",
      create: "Tạo tin",
      comingSoon: "Tính năng Tin sẽ có sớm.",
      placeholders: ["Mùa vụ mới", "Thu hoạch", "Chợ tuần này", "Mẹo canh tác", "Cộng đồng HTX"],
    },
    suggestions: {
      title: "Gợi ý cho bạn",
      seeAll: "Xem tất cả",
      seeAllHref: ROUTES.marketplace,
      comingSoon: "Tính năng kết nối sẽ có sớm.",
      items: [
        {
          id: "suggestion-dalat-coop",
          href: ROUTES.marketplace,
          name: "HTX Rau Sạch Đà Lạt",
          subtitle: "3 bạn chung quan tâm nông sản xanh",
          action: "Theo dõi",
          emoji: "🥬",
        },
        {
          id: "suggestion-weekly-market",
          href: ROUTES.marketplace,
          name: "Chợ nông sản tuần",
          subtitle: "Sản phẩm mới từ người bán gần bạn",
          action: "Khám phá",
          emoji: "🛒",
        },
        {
          id: "suggestion-green-profile",
          href: ROUTES.greenProfile,
          name: "Hồ sơ xanh mẫu",
          subtitle: "Xem chuẩn nhật ký canh tác đầy đủ",
          action: "Xem hồ sơ",
          emoji: "🌿",
        },
        {
          id: "suggestion-trace-demo",
          href: ROUTES.trace("demo"),
          name: "Demo truy xuất QR",
          subtitle: "Trải nghiệm quét mã từ vườn đến bàn",
          action: "Xem demo",
          emoji: "📱",
        },
      ],
    },
    feed: {
      pageTitle: "Bảng tin",
      pageSubtitle: "Cập nhật từ cộng đồng nông nghiệp xanh",
      emptyTitle: "Chưa có bài viết nào",
      emptyDescription:
        "Chia sẻ mùa vụ, thu hoạch hoặc ảnh vườn — bài đầu tiên sẽ hiện ngay tại đây.",
      emptyAction: "Đăng bài đầu tiên",
      loadError: "Không tải được bảng tin.",
      loadMore: "Xem thêm bài viết",
      loading: "Đang tải...",
      searchPlaceholder: "Tìm kiếm bài viết...",
      searchEmpty: "Không tìm thấy bài viết nào.",
      searchError: "Không tải được kết quả tìm kiếm.",
    },
    detail: {
      loadError: "Không tải được bài viết.",
      forbidden: "Bạn không có quyền xem bài viết này.",
      notFound: "Bài viết không tồn tại hoặc đã bị xóa.",
      backToFeed: "Về bảng tin",
      railTitle: "Bài viết",
      railDescription: "Bình luận và phản hồi nằm ngay bên dưới nội dung bài viết.",
      dialogTitle: (name: string) => `Bài viết của ${name}`,
      dialogTitleFallback: "Bài viết",
      close: "Đóng",
    },
    feedAside: {
      profileSection: "Hồ sơ xanh",
      statPosts: "Bài viết",
      statFollowing: "Theo dõi",
      statProducts: "Sản phẩm",
      productsSection: "Sản phẩm gợi ý",
      sellersSection: "Gợi ý người bán",
      seeAll: "Xem tất cả",
      follow: "Theo dõi",
      trendingSection: "Xu hướng xanh",
      seeMoreTrends: "Xem thêm xu hướng →",
    },
    post: {
      like: "Thích",
      comment: "Bình luận",
      share: "Chia sẻ",
      menu: "Tùy chọn bài viết",
      edit: "Chỉnh sửa",
      delete: "Xóa bài",
      copyLink: "Sao chép liên kết",
      report: "Báo cáo",
      block: "Chặn người đăng",
      comingSoon: "Tính năng này sẽ có sớm.",
      reactionsSummary: (count: number) => `${count} lượt thích`,
      commentsSummary: (count: number) => `${count} bình luận`,
      roles: {
        CONSUMER: "Người mua",
        SELLER: "Người bán",
        COOPERATIVE: "HTX",
        ENTERPRISE: "Doanh nghiệp",
        EXPERT: "Chuyên gia",
        ADMIN: "Quản trị",
        GUEST: "Khách",
      } as Record<string, string>,
    },
    editDialog: {
      title: "Chỉnh sửa bài viết",
      description: "Cập nhật nội dung và nhãn — ảnh trong bài giữ nguyên.",
      bodyLabel: "Nội dung",
      save: "Lưu",
      saving: "Đang lưu...",
      cancel: "Hủy",
      empty: "Nhập nội dung hoặc giữ ảnh trong bài.",
    },
    deleteDialog: {
      title: "Xóa bài viết?",
      description: "Bài viết sẽ bị xóa và không thể khôi phục.",
      confirm: "Xóa",
      deleting: "Đang xóa...",
      cancel: "Hủy",
    },
    aside: {
      sponsoredTitle: "Được tài trợ",
      sponsored: [
        {
          href: ROUTES.marketplace,
          name: "Kết nối người mua — VietGreenX",
          domain: "vietgreenx.vn/chợ",
          accent: "secondary" as const,
        },
        {
          href: ROUTES.pricing,
          name: "Nâng cấp gói bán hàng",
          domain: "vietgreenx.vn/gói-dịch-vụ",
          accent: "primary" as const,
        },
      ],
      contactsTitle: "Người liên hệ",
      contacts: [
        { name: "Hỗ trợ VietGreenX", status: "Sẵn sàng trò chuyện" },
        { name: "Cộng đồng nông dân", status: "12 thành viên online" },
      ],
      discoverTitle: "Khám phá",
      discover: [
        {
          href: ROUTES.marketplace,
          name: "Chợ nông sản",
          description: "Kết nối người mua — nguồn gốc rõ ràng",
          accent: "secondary" as const,
        },
        {
          href: ROUTES.greenProfile,
          name: "Hồ sơ xanh",
          description: "Chuẩn sản xuất & nhật ký canh tác",
          accent: "primary" as const,
        },
        {
          href: ROUTES.qr,
          name: "QR truy xuất",
          description: "Quét mã — minh bạch từ vườn đến bàn",
          accent: "tertiary" as const,
        },
        {
          href: ROUTES.trace("demo"),
          name: "Xem demo truy xuất",
          description: "Trang công khai khi khách quét mã QR",
          accent: "trace" as const,
        },
      ],
      tipsTitle: "Mẹo nông nghiệp",
      tips: [
        "Ghi nhật ký thu hoạch trong Hồ sơ xanh để tăng độ tin cậy.",
        "Đăng ảnh rõ nét giúp người mua dễ nhận diện sản phẩm.",
        "Cập nhật địa chỉ vườn để khách hàng gần bạn tìm thấy dễ hơn.",
      ],
    },
    toast: {
      created: "Đã đăng bài.",
      createError: "Không thể đăng bài. Vui lòng thử lại.",
      updated: "Đã cập nhật bài viết.",
      updateError: "Không thể cập nhật bài viết.",
      deleted: "Đã xóa bài viết.",
      deleteError: "Không thể xóa bài viết.",
      hashtagLimit: "Tối đa 30 hashtag trong nội dung bài.",
      linkCopied: "Đã sao chép liên kết bài viết.",
      shareFailed: "Không thể chia sẻ liên kết.",
    },
    vietShop: {
      badge: "VietShopX247",
      cta: "Xem trên cửa hàng đối tác",
      composerHint: "Thêm #vietshop để hiện preview liên kết cửa hàng (demo layout).",
    },
    feedTabs: {
      all: "Tất cả",
      following: "Theo dõi",
      produce_story: "Câu chuyện nông sản",
      crop_journal: "Nhật ký mùa vụ",
      farming_technique: "Kỹ thuật canh tác",
      market_price: "Giá thị trường",
      trade_connection: "Giao thương",
      ocop_vietgap: "OCOP / VietGAP",
    },
  },
  en: {
    composer: {
      title: "Share with the community",
      placeholder: "What's on your mind about green agriculture today?",
      photo: "Photo/Video",
      greenProfile: "Products",
      marketplace: "QR trace",
      submit: "Post",
      submitting: "Posting...",
      cancel: "Cancel",
      empty: "Add text or choose a photo.",
      imageInvalidType: "PNG, JPG or WebP only.",
      imageTooLarge: "Max 5MB.",
      removeImage: "Remove photo",
      contentCategory: "Post type",
      contentCategoryPlaceholder: "Choose post type (optional)",
      contentCategoryNone: "No post type",
      more: "More",
      moreOptions: "Post options",
    },
    tags: {
      title: "Tag this post",
      hint: "Help readers see related products, regions, and catalog categories.",
      listAria: "Post tags",
      metaAria: "Post context",
      remove: "Remove tag",
      region: "Region",
      catalogCategory: "Category",
      product: "Product",
      productSearch: "Search products...",
      productEmpty: "No products yet.",
      maxReached: "Maximum 20 tags per post.",
      regionPlaceholder: "Select province / region",
      regionSearch: "Search province...",
      regionEmpty: "No region found.",
      categoryPlaceholder: "Select category",
      categorySearch: "Search category...",
      categoryEmpty: "No category found.",
      types: {
        region: "Region",
        category: "Category",
        product: "Product",
      },
    },
    hashtags: {
      useCustom: (tag: string) => `Create #${tag}`,
      searchError: "Could not load hashtag suggestions. You can still type #tags manually.",
      postCount: (count: number) => `${count} posts`,
      limitExceeded: "Maximum 30 hashtags per post.",
      exploreComingSoon: "Browse posts by hashtag is coming soon.",
    },
    postContentCategory: {
      produce_story: "Produce story",
      crop_journal: "Crop journal",
      farming_technique: "Farming technique",
      market_price: "Market price",
      trade_connection: "Trade connection",
      ocop_vietgap_story: "OCOP / VietGAP",
    },
    stories: {
      ariaLabel: "Stories",
      create: "Create story",
      comingSoon: "Stories are coming soon.",
      placeholders: ["New season", "Harvest", "Market week", "Farm tips", "Co-op news"],
    },
    suggestions: {
      title: "Suggested for you",
      seeAll: "See all",
      seeAllHref: ROUTES.marketplace,
      comingSoon: "Connections are coming soon.",
      items: [
        {
          id: "suggestion-dalat-coop",
          href: ROUTES.marketplace,
          name: "Da Lat Fresh Co-op",
          subtitle: "3 mutual connections in green ag",
          action: "Follow",
          emoji: "🥬",
        },
        {
          id: "suggestion-weekly-market",
          href: ROUTES.marketplace,
          name: "Weekly marketplace",
          subtitle: "New listings from sellers near you",
          action: "Explore",
          emoji: "🛒",
        },
        {
          id: "suggestion-green-profile",
          href: ROUTES.greenProfile,
          name: "Sample green profile",
          subtitle: "See a complete farm log example",
          action: "View profile",
          emoji: "🌿",
        },
        {
          id: "suggestion-trace-demo",
          href: ROUTES.trace("demo"),
          name: "QR trace demo",
          subtitle: "Try the farm-to-table scan flow",
          action: "View demo",
          emoji: "📱",
        },
      ],
    },
    feed: {
      pageTitle: "Feed",
      pageSubtitle: "Updates from the green agriculture community",
      emptyTitle: "No posts yet",
      emptyDescription:
        "Share your harvest, season updates or farm photos — your first post appears here.",
      emptyAction: "Create your first post",
      loadError: "Could not load feed.",
      loadMore: "Load more posts",
      loading: "Loading...",
      searchPlaceholder: "Search posts...",
      searchEmpty: "No posts found.",
      searchError: "Could not load search results.",
    },
    detail: {
      loadError: "Could not load post.",
      forbidden: "You do not have permission to view this post.",
      notFound: "This post does not exist or was removed.",
      backToFeed: "Back to feed",
      railTitle: "Post",
      railDescription: "Comments and replies appear below the post content.",
      dialogTitle: (name: string) => `Post by ${name}`,
      dialogTitleFallback: "Post",
      close: "Close",
    },
    feedAside: {
      profileSection: "Green profile",
      statPosts: "Posts",
      statFollowing: "Following",
      statProducts: "Products",
      productsSection: "Suggested products",
      sellersSection: "Suggested sellers",
      seeAll: "See all",
      follow: "Follow",
      trendingSection: "Green trends",
      seeMoreTrends: "See more trends →",
    },
    post: {
      like: "Like",
      comment: "Comment",
      share: "Share",
      menu: "Post options",
      edit: "Edit",
      delete: "Delete post",
      copyLink: "Copy link",
      report: "Report",
      block: "Block author",
      comingSoon: "This feature is coming soon.",
      reactionsSummary: (count: number) => `${count} reactions`,
      commentsSummary: (count: number) => `${count} comments`,
      roles: {
        CONSUMER: "Buyer",
        SELLER: "Seller",
        COOPERATIVE: "Cooperative",
        ENTERPRISE: "Enterprise",
        EXPERT: "Expert",
        ADMIN: "Admin",
        GUEST: "Guest",
      } as Record<string, string>,
    },
    editDialog: {
      title: "Edit post",
      description: "Update text and tags — photos in this post stay the same.",
      bodyLabel: "Content",
      save: "Save",
      saving: "Saving...",
      cancel: "Cancel",
      empty: "Add text or keep the photo in this post.",
    },
    deleteDialog: {
      title: "Delete post?",
      description: "This post will be removed and cannot be restored.",
      confirm: "Delete",
      deleting: "Deleting...",
      cancel: "Cancel",
    },
    aside: {
      sponsoredTitle: "Sponsored",
      sponsored: [
        {
          href: ROUTES.marketplace,
          name: "Connect with buyers — VietGreenX",
          domain: "vietgreenx.vn/market",
          accent: "secondary" as const,
        },
        {
          href: ROUTES.pricing,
          name: "Upgrade seller plan",
          domain: "vietgreenx.vn/pricing",
          accent: "primary" as const,
        },
      ],
      contactsTitle: "Contacts",
      contacts: [
        { name: "VietGreenX Support", status: "Available to chat" },
        { name: "Farmer community", status: "12 members online" },
      ],
      discoverTitle: "Discover",
      discover: [
        {
          href: ROUTES.marketplace,
          name: "Marketplace",
          description: "Connect with buyers — clear origins",
          accent: "secondary" as const,
        },
        {
          href: ROUTES.greenProfile,
          name: "Green profile",
          description: "Production standards & farm logs",
          accent: "primary" as const,
        },
        {
          href: ROUTES.qr,
          name: "QR traceability",
          description: "Scan codes — farm to table transparency",
          accent: "tertiary" as const,
        },
        {
          href: ROUTES.trace("demo"),
          name: "Trace demo",
          description: "Public page shoppers see when scanning QR",
          accent: "trace" as const,
        },
      ],
      tipsTitle: "Farm tips",
      tips: [
        "Log harvests in Green Profile to build trust with buyers.",
        "Clear photos help buyers recognize your products.",
        "Keep your farm address updated so nearby customers can find you.",
      ],
    },
    toast: {
      created: "Post published.",
      createError: "Could not publish. Please try again.",
      updated: "Post updated.",
      updateError: "Could not update post.",
      deleted: "Post deleted.",
      deleteError: "Could not delete post.",
      hashtagLimit: "Maximum 30 hashtags per post.",
      linkCopied: "Post link copied.",
      shareFailed: "Could not share link.",
    },
    vietShop: {
      badge: "VietShopX247",
      cta: "View on partner storefront",
      composerHint: "Add #vietshop to show storefront link preview (layout demo).",
    },
    feedTabs: {
      all: "All",
      following: "Following",
      produce_story: "Produce Stories",
      crop_journal: "Crop Journal",
      farming_technique: "Farming Technique",
      market_price: "Market Price",
      trade_connection: "Trade Connection",
      ocop_vietgap: "OCOP / VietGAP",
    },
  },
} as const;

export function getPostsCopy(locale: AppLocale) {
  return POSTS_COPY[locale] ?? POSTS_COPY.vi;
}
