import type { ActivityType } from "@/entities/production-log";
import type { AppLocale } from "@/shared/i18n/locale";

export const ACTIVITY_TYPES: ActivityType[] = [
  "sowing",
  "caring",
  "fertilizing",
  "spraying",
  "irrigating",
  "harvesting",
  "other",
];

const PRODUCTION_LOG_VALIDATION_COPY = {
  vi: {
    cropSeasonRequired: "Vui lòng chọn mùa vụ",
    activityTypeRequired: "Vui lòng chọn loại hoạt động",
    logDateRequired: "Vui lòng chọn ngày ghi nhận",
    noteBodyRequired: "Vui lòng nhập nội dung ghi chú",
  },
  en: {
    cropSeasonRequired: "Please select a crop season",
    activityTypeRequired: "Please select an activity type",
    logDateRequired: "Please select a log date",
    noteBodyRequired: "Please enter a note",
  },
} as const;

export function getProductionLogValidationCopy(locale: AppLocale) {
  return PRODUCTION_LOG_VALIDATION_COPY[locale] ?? PRODUCTION_LOG_VALIDATION_COPY.vi;
}

const PRODUCTION_LOG_COPY = {
  vi: {
    timeline: {
      title: "Nhật ký sản xuất",
      subtitle: "Ghi chép bất biến — không sửa hoặc xóa sau khi lưu.",
      addCta: "Ghi nhật ký",
      emptyTitle: "Chưa có nhật ký",
      emptyDescription: "Ghi lại gieo hạt, chăm sóc, thu hoạch để minh bạch quy trình sản xuất.",
      appendOnlyNote: "Nhật ký chỉ thêm mới, phục vụ truy xuất nguồn gốc.",
      loadError: "Không thể tải nhật ký sản xuất.",
      loading: "Đang tải...",
      filterLabel: "Bộ lọc:",
      allFilter: "Tất cả",
      seasonLabel: "Mùa vụ:",
      allSeasonsFilter: "Tất cả mùa vụ",
      noFilterResults: "Không tìm thấy nhật ký sản xuất phù hợp với bộ lọc.",
      verifiedBadge: "Ghi nhận minh bạch",
      noNotes: "Không có ghi chú thêm",
      previousPage: "Trang trước",
      nextPage: "Trang sau",
    },
    form: {
      title: "Ghi nhật ký sản xuất",
      subtitle: "Nhật ký chỉ thêm mới — không sửa hoặc xóa sau khi lưu.",
      fields: {
        cropSeason: "Mùa vụ",
        activityType: "Loại hoạt động",
        logDate: "Ngày ghi nhận",
        notes: "Ghi chú",
        inputMaterial: "Vật tư đầu vào",
        dosage: "Liều lượng",
        dosageUnit: "Đơn vị",
        weather: "Thời tiết",
        pestStatus: "Tình trạng sâu bệnh",
        estimatedYield: "Sản lượng ước tính (tấn)",
        media: "Ảnh / Video đính kèm",
      },
      cropSeasonNone: "Chọn mùa vụ",
      noSeasons: "Cần tạo mùa vụ trước khi ghi nhật ký.",
      submit: "Lưu nhật ký",
      mediaUploadError: "Không thể tải ảnh lên. Vui lòng thử lại.",
      mediaSizeError: "Ảnh không được vượt quá 10MB.",
      mediaTypeError: "Chỉ hỗ trợ ảnh JPEG, PNG, WebP.",
    },
    activityTypes: {
      sowing: "Gieo hạt",
      caring: "Chăm sóc",
      fertilizing: "Bón phân",
      spraying: "Phun thuốc",
      irrigating: "Tưới nước",
      harvesting: "Thu hoạch",
      other: "Khác",
    } satisfies Record<ActivityType, string>,
    toast: {
      createSuccess: "Đã ghi nhật ký sản xuất.",
      createError: "Không thể ghi nhật ký. Vui lòng thử lại.",
      noteSuccess: "Đã thêm ghi chú.",
      noteError: "Không thể thêm ghi chú.",
    },
    loadError: "Không thể tải nhật ký sản xuất.",
    detail: {
      title: "Chi tiết nhật ký",
      subtitle: "Xem thông tin và thêm ghi chú bổ sung.",
      fields: {
        activityType: "Hoạt động",
        logDate: "Ngày ghi nhận",
        notes: "Ghi chú mới nhất",
        inputMaterial: "Vật tư đầu vào",
        dosage: "Liều lượng",
        weather: "Thời tiết",
        pestStatus: "Tình trạng sâu bệnh",
        estimatedYield: "Sản lượng ước tính",
      },
      addNote: "Thêm ghi chú",
      notePlaceholder: "Nhập ghi chú bổ sung...",
      noteDisabled: "Không thể thêm ghi chú khi mùa vụ đã kết thúc.",
      additionalNotesTitle: "Lịch sử ghi chú bổ sung",
      mediaTitle: "Ảnh đính kèm",
      mediaCount: (n: number) => `${n} ảnh / video đính kèm`,
      view: "Xem",
      loading: "Đang tải...",
      loadError: "Không thể tải chi tiết nhật ký.",
    },
    qrSummary: {
      title: "Tóm tắt 5 mốc QR",
      subtitle: "Nhóm nhật ký theo mốc hoạt động cho trang truy xuất.",
      seasonLabel: "Mùa vụ",
      emptyMilestone: "Chưa có nhật ký",
      loading: "Đang tải tóm tắt...",
      loadError: "Không thể tải tóm tắt QR.",
      noSeason: "Chọn mùa vụ để xem tóm tắt.",
      recordCount: (n: number) => `${n} ghi nhận`,
      pendingStatus: "Chờ thực hiện",
    },
  },
  en: {
    timeline: {
      title: "Production log",
      subtitle: "Immutable records — no edit or delete after save.",
      addCta: "Add log entry",
      emptyTitle: "No log entries yet",
      emptyDescription: "Record sowing, care, and harvest for transparent traceability.",
      appendOnlyNote: "Append-only log for origin traceability.",
      loadError: "Could not load production logs.",
      loading: "Loading...",
      filterLabel: "Filter:",
      allFilter: "All",
      seasonLabel: "Crop season:",
      allSeasonsFilter: "All crop seasons",
      noFilterResults: "No production logs match the selected filter.",
      verifiedBadge: "Verified Log",
      noNotes: "No additional notes",
      previousPage: "Previous",
      nextPage: "Next",
    },
    form: {
      title: "Add production log",
      subtitle: "Logs are append-only — they cannot be edited or deleted.",
      fields: {
        cropSeason: "Crop season",
        activityType: "Activity type",
        logDate: "Log date",
        notes: "Notes",
        inputMaterial: "Input material",
        dosage: "Dosage",
        dosageUnit: "Unit",
        weather: "Weather",
        pestStatus: "Pest status",
        estimatedYield: "Estimated yield (tonnes)",
        media: "Photos / Videos",
      },
      cropSeasonNone: "Select a season",
      noSeasons: "Create a crop season before adding logs.",
      submit: "Save log",
      mediaUploadError: "Could not upload image. Please try again.",
      mediaSizeError: "Image must not exceed 10 MB.",
      mediaTypeError: "Only JPEG, PNG, and WebP images are supported.",
    },
    activityTypes: {
      sowing: "Sowing",
      caring: "Care",
      fertilizing: "Fertilizing",
      spraying: "Spraying",
      irrigating: "Irrigating",
      harvesting: "Harvesting",
      other: "Other",
    } satisfies Record<ActivityType, string>,
    toast: {
      createSuccess: "Production log saved.",
      createError: "Could not save log. Please try again.",
      noteSuccess: "Note added.",
      noteError: "Could not add note.",
    },
    loadError: "Could not load production logs.",
    detail: {
      title: "Log details",
      subtitle: "View log information and append additional notes.",
      fields: {
        activityType: "Activity",
        logDate: "Log date",
        notes: "Latest note",
        inputMaterial: "Input material",
        dosage: "Dosage",
        weather: "Weather",
        pestStatus: "Pest status",
        estimatedYield: "Estimated yield",
      },
      addNote: "Add note",
      notePlaceholder: "Enter an additional note...",
      noteDisabled: "Notes cannot be added after the season has ended.",
      additionalNotesTitle: "Additional notes history",
      mediaTitle: "Attached photos",
      mediaCount: (n: number) => `${n} photo(s) / video(s) attached`,
      view: "View",
      loading: "Loading...",
      loadError: "Could not load log details.",
    },
    qrSummary: {
      title: "5-milestone QR summary",
      subtitle: "Production logs grouped by milestone for traceability.",
      seasonLabel: "Crop season",
      emptyMilestone: "No logs yet",
      loading: "Loading summary...",
      loadError: "Could not load QR summary.",
      noSeason: "Select a season to view the summary.",
      recordCount: (n: number) => `${n} record(s)`,
      pendingStatus: "Pending",
    },
  },
} as const;

export function getProductionLogCopy(locale: AppLocale) {
  return PRODUCTION_LOG_COPY[locale] ?? PRODUCTION_LOG_COPY.vi;
}
